const TF_FORMULA={
  level:{en:"x = value as published",pl:"x = wartość jak opublikowana"},
  yoy:{en:"x = 100 × (v<sub>t</sub> / v<sub>t−12m</sub> − 1)",pl:"x = 100 × (v<sub>t</sub> / v<sub>t−12m</sub> − 1)"},
  qoq_saar:{en:"x = 100 × ((v<sub>t</sub> / v<sub>t−3m</sub>)<sup>4</sup> − 1)",pl:"x = 100 × ((v<sub>t</sub> / v<sub>t−3m</sub>)<sup>4</sup> − 1)"},
  chg12:{en:"x = v<sub>t</sub> − v<sub>t−12m</sub>",pl:"x = v<sub>t</sub> − v<sub>t−12m</sub>"},
  mchg_avg3:{en:"x = 3-month average of the monthly change",pl:"x = średnia 3-miesięczna zmiany miesięcznej"},
  ma4w:{en:"x = 4-week moving average",pl:"x = 4-tygodniowa średnia krocząca"},
  pchg13w:{en:"x = 100 × (v<sub>t</sub> / v<sub>t−91d</sub> − 1)",pl:"x = 100 × (v<sub>t</sub> / v<sub>t−91d</sub> − 1)"},
  drawdown:{en:"x = 100 × (v<sub>t</sub> / 365-day high − 1)",pl:"x = 100 × (v<sub>t</sub> / maksimum z 365 dni − 1)"},
  pctgdp:{en:"x = 100 × v / (nominal GDP × 1000), GDP carried up to 200 days",pl:"x = 100 × v / (PKB nominalny × 1000), PKB przenoszony do 200 dni"},
  sum12m_pctgdp:{en:"x = 100 × (12-month sum of v) / (nominal GDP × 1000)",pl:"x = 100 × (suma 12-miesięczna v) / (PKB nominalny × 1000)"},
  real_pce:{en:"x = monthly mean of the policy rate − core PCE inflation y/y",pl:"x = średnia miesięczna stopy polityki − bazowa inflacja PCE r/r"},
  spread_iorb:{en:"x = rate − interest on reserve balances (IOER before 2021-07-29)",pl:"x = stopa − oprocentowanie rezerw (IOER przed 2021-07-29)"},
  ratio_unemploy:{en:"x = job openings / unemployed persons (UNEMPLOY)",pl:"x = wolne miejsca pracy / osoby bezrobotne (UNEMPLOY)"},
  ratio_vix_vxv:{en:"x = VIX / 3-month VIX on common dates",pl:"x = VIX / 3-miesięczny VIX we wspólnych datach"},
  minus100:{en:"x = v − 100 (GUS indices with the previous year = 100)",pl:"x = v − 100 (indeksy GUS, rok poprzedni = 100)"},
  sum12m:{en:"x = 12-month sum of v",pl:"x = suma 12-miesięczna v"},
  zpass:{en:"x = the series itself, already a z-score (the YieldCartography liquidity composite)",pl:"x = sam szereg, który już jest wynikiem z (złożona miara płynności YieldCartography)"}
};
function renderApp(){
  const box=$("appBody"); if(!box) return;
  const ser=(DATA&&DATA.series)||{}, ids=Object.keys(ser).filter(i=>!ser[i].virtual).sort((a,b)=>(ser[a].group-ser[b].group)||a.localeCompare(b)), W=effHeadW();
  const grp={}; ((DATA&&DATA.groups)||[]).forEach(g=>grp[g.id]=g.name);
  const usedTf={}; ids.forEach(i=>{ const s=ser[i]; if(s.stats&&s.stats.transform) usedTf[s.stats.transform]=(usedTf[s.stats.transform]||0)+1; });
  const PLL=LANG==="pl", US=CP.code==="us", T=(en,pl)=>PLL?pl:en;
  const inDial=(i,s,st)=>String(s.group)==="0"?T("recession block","blok recesji"):!st?T("not scored","bez oceny"):st.scored===false?T("display only","tylko do wglądu"):mW(i)>0?T("yes","tak"):T("dropped (Assumptions)","usunięty (Założenia)");
  const cat=`<tr><th class='l'>Id</th><th class='l'>${T("Series","Szereg")}</th><th class='l'>${T("Group","Grupa")}</th><th class='l'>${T("Freq","Częst.")}</th><th class='l'>${T("Scored as","Oceniany jako")}</th><th>${T("Polarity","Kierunek")}</th><th class='l'>${T("In the dials","W tarczach")}</th><th class='l'>${T("Rights","Prawa")}</th><th class='l'>${T("Source","Źródło")}</th></tr>`
    +ids.map(i=>{ const s=ser[i], st=s.stats; return `<tr><td class="l"><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(i)}</a></td><td class="l">${esc(s.label)}</td><td class="l">${esc(grp[s.group]||s.group)}</td><td class="l">${esc(TR(s.freq))}</td>`
      +`<td class="l">${st&&st.transform?esc(st.transform):"–"}</td><td>${(+s.polarity||1)>0?"+1":"−1"}</td><td class="l">${inDial(i,s,st)}</td><td class="l">${esc(s.publish)}</td><td class="l" style="font-size:10.5px;color:var(--muted)">${esc(s.source)}</td></tr>`; }).join("");
  const wtxt=H_KEYS.map(([k,n])=>`${n}: `+Object.keys(W[k]).filter(g=>W[k][g]>0).map(g=>`${esc(gName(g))} ${fmt(100*W[k][g],0)}%`).join(", ")).join("<br>");
  const cuts=Object.entries(CUT_KINDS).map(([k,K])=>`<tr><td class="l">${esc(K.n)}</td><td class="l">${K.zones().map(z=>`<span class="zchip" style="background:${z.c}">${esc(z.n)}</span> ${fmt(z.a<K.lo?K.lo:z.a,k==="fisc"?1:0)} ${T("to","do")} ${fmt(z.b>K.hi?K.hi:z.b,k==="fisc"?1:0)}`).join(" &nbsp; ")}</td></tr>`).join("");
  const built=DATA?esc(DATA.built_at||""):"", asof=DATA?esc(DATA.data_as_of||""):"", ch=assumeChanges();
  const tfList=Object.entries(usedTf).map(([k,n])=>`${esc(k)} (${n})`).join(", ");
  const tfTable=`<table class="res">${Object.keys(TF_FORMULA).filter(k=>usedTf[k]).map(k=>`<tr><td class="l" style="width:140px"><code>${k}</code></td><td class="l">${L(TF_FORMULA[k])}</td></tr>`).join("")}</table>`;
  const recSet=`<b>${esc(TR(ASSUME.rec.method))}</b> ${T("of","z")} ${Object.keys(ASSUME.rec.parts).filter(k=>ASSUME.rec.parts[k]).map(esc).join(", ")}`;
  const gh=ASSUME.view.ghost, ar=ASSUME.view.arrow, y0=histY(), nSer=ids.length;
  const mo=n=>PLL?`${n} ${plN(n,"miesiąc","miesiące","miesięcy")}`:`${n} month${n>1?"s":""}`;
  const S={};   // sections, keyed by number: [title, html]
  // 1
  S[1]=[T("What this dashboard is","Czym jest ten pulpit"),
    (US?T(`<p>Macro Radar summarises the US economy from public FRED data. About 130 series are turned into comparable scores, averaged into eight group dials and four headline gauges (economy, policy stance, financial conditions, price pressure), plus a recession-risk gauge. The policy stance blends monetary policy with the fiscal impulse. It is an informational view of public data. It is not a forecast, and it is not built or validated for reports, limits or decisions.</p>`,
           `<p>Macro Radar podsumowuje gospodarkę USA na podstawie publicznych danych FRED. Około 130 szeregów zamienia się na porównywalne wyniki, uśrednione w osiem tarcz grup i cztery wskaźniki główne (gospodarka, nastawienie polityki, warunki finansowe, presja cenowa) oraz wskaźnik ryzyka recesji. Nastawienie polityki łączy politykę pieniężną z impulsem fiskalnym. To informacyjny przegląd danych publicznych. Nie jest prognozą i nie został zbudowany ani zwalidowany do raportów, limitów czy decyzji.</p>`)
       :T(`<p>Macro Radar Poland summarises the Polish economy from public statistics. About ${nSer} series are turned into comparable scores, averaged into eight group dials and four headline gauges (economy, policy stance, financial conditions, price pressure), plus a recession-risk reading. The policy stance blends monetary policy with the fiscal impulse. The method is the one of the US Macro Radar: each indicator is transformed as its registry row says, standardised as a robust z over a rolling ten-year window (expanding from five years), signed by its polarity and clipped at &plusmn;3, and averaged with equal weights into its group; a dial is 100 &Phi;(z). It is an informational view of public data. It is not a forecast, and it is not built or validated for reports, limits or decisions.</p>`,
           `<p>Macro Radar Polska podsumowuje polską gospodarkę na podstawie publicznych statystyk. Około ${nSer} szeregów zamienia się na porównywalne wyniki, uśrednione w osiem tarcz grup i cztery wskaźniki główne (gospodarka, nastawienie polityki, warunki finansowe, presja cenowa) oraz odczyt ryzyka recesji. Nastawienie polityki łączy politykę pieniężną z impulsem fiskalnym. Metoda jest taka sama jak w amerykańskim Macro Radar: każdy wskaźnik jest przekształcany zgodnie ze swoim wierszem w rejestrze, standaryzowany jako odporny wynik z w kroczącym oknie dziesięcioletnim (rozszerzanym od pięciu lat), opatrywany znakiem kierunku, obcinany do &plusmn;3 i uśredniany z równymi wagami w swojej grupie; tarcza to 100 &Phi;(z). To informacyjny przegląd danych publicznych. Nie jest prognozą i nie został zbudowany ani zwalidowany do raportów, limitów czy decyzji.</p>`))
    +T(`<p>This copy: data as of <b>${asof}</b>, built ${built}. ${ch.length?`Settings changed on the Assumptions tab: ${esc(ch.join(", "))}. The numbers below that depend on them reflect these settings.`:"All settings are the defaults: the engine's numbers, with the policy stance blended with the fiscal impulse in this page."}</p>`,
       `<p>Ta kopia: dane na <b>${asof}</b>, zbudowane ${built}. ${ch.length?`Ustawienia zmienione w zakładce Założenia: ${esc(ch.join(", "))}. Zależne od nich liczby poniżej odzwierciedlają te ustawienia.`:"Wszystkie ustawienia są domyślne: liczby silnika, z nastawieniem polityki połączonym na tej stronie z impulsem fiskalnym."}</p>`)
    +T(`<p>The page is one of two radars on macrocartography.com, the United States and Poland, built from the same template. The flags next to the logo switch the country's data; EN and PL switch the language of the page and are independent of the country, so either radar can be read in either language. Official source titles and citations stay as each source publishes them.</p>`,
       `<p>Strona jest jednym z dwóch radarów w serwisie macrocartography.com, dla Stanów Zjednoczonych i dla Polski, zbudowanych z tego samego szablonu. Flagi obok logo przełączają dane kraju; EN i PL przełączają język strony niezależnie od kraju, więc każdy radar można czytać w każdym z dwóch języków. Oficjalne tytuły i cytowania źródeł pozostają w brzmieniu nadanym przez źródło.</p>`)];
  // 2
  S[2]=[T("Data and refresh","Dane i odświeżanie"),
    T(`<p><b>History tab.</b> Long series over the regime canvas. Each chosen series is reduced to monthly means (daily and weekly data averaged by calendar month, monthly and slower data as published) and drawn over a canvas that colours every month by the regime compass quadrant of its growth and price-pressure z: Overheating (both at or above the cut-offs), Stagflation (growth below, prices above), Slowdown (both below), Goldilocks (growth above, prices below); grey where the compass has no reading. The cut-offs, 0 and 0 in the engine, are editable on the Assumptions tab and on the History tab and move the compass itself. A range of months can be chosen: outside it the canvas and the lines are paled, and the table splits the range by regime with the number of months, their share, and the mean and standard deviation of each series over the monthly means in that regime, plus the whole range regardless of regime. The default set is ${L(CP.histDefaultTxt)}; any published series can be added, on a right-hand axis when its units differ.</p>`,
      `<p><b>Zakładka Historia.</b> Długie szeregi na tle reżimów. Każdy wybrany szereg sprowadza się do średnich miesięcznych (dane dzienne i tygodniowe uśrednione w miesiącach kalendarzowych, miesięczne i rzadsze jak opublikowano) i rysuje na tle, które barwi każdy miesiąc według ćwiartki kompasu reżimów wyznaczonej przez z wzrostu i z presji cenowej: Przegrzanie (oba na progach lub powyżej), Stagflacja (wzrost poniżej, ceny powyżej), Spowolnienie (oba poniżej), Złoty środek (wzrost powyżej, ceny poniżej); szare tam, gdzie kompas nie ma odczytu. Progi, w silniku 0 i 0, można zmieniać w zakładkach Założenia i Historia; przesuwają też sam kompas. Można wybrać zakres miesięcy: poza nim tło i linie są wyblakłe, a tabela dzieli zakres według reżimów, podając liczbę miesięcy, ich udział oraz średnią i odchylenie standardowe każdego szeregu ze średnich miesięcznych w danym reżimie, a także cały zakres bez podziału. Zestaw domyślny to ${L(CP.histDefaultTxt)}; można dodać dowolny publikowany szereg, na prawej osi, gdy ma inne jednostki.</p>`)
    +(US?T(`<p>Every weekday the YieldCartography pipeline downloads each series from FRED's public CSV endpoint (fredgraph.csv) and merges it into a stored history. To catch revisions it re-downloads the last 60 days of daily and weekly series, the last 36 months of monthly and quarterly series and the last 5 years of annual ones, and the new download wins from its first date onward. The pipeline then rebuilds one JSON file (schema <code>macro_radar/v1</code>). This page reads it from macrocartography.com/data/us.json, and the older address yieldcartography.com/data/macro/macro_radar.json still answers.</p>
<p>The file keeps daily series at full detail for the last three years and thins them to weekly before that. Five series that FRED marks as needing the owner's pre-approval are never published (two ICE BofA spreads, the S&amp;P/Case-Shiller index, the S&amp;P 500 and the NASDAQ Composite). FHFA house prices and Moody's Baa and Aaa spreads stand in, and VIX carries the equity signal. Five helper series are fetched for splices and denominators but not shown (IOER, the daily federal funds rate, the pre-2008 single target rate, unemployed persons and nominal GDP), plus GS10 and TB3MS for the yield-curve model.</p>`,
      `<p>W każdy dzień roboczy proces YieldCartography pobiera każdy szereg z publicznego punktu CSV serwisu FRED (fredgraph.csv) i dołącza go do przechowywanej historii. Aby uchwycić rewizje, ponownie pobiera ostatnie 60 dni szeregów dziennych i tygodniowych, ostatnie 36 miesięcy miesięcznych i kwartalnych oraz ostatnie 5 lat rocznych, a nowe pobranie zastępuje dane od swojej pierwszej daty. Następnie proces buduje jeden plik JSON (schemat <code>macro_radar/v1</code>). Ta strona czyta go z macrocartography.com/data/us.json; dawny adres yieldcartography.com/data/macro/macro_radar.json nadal działa.</p>
<p>Plik zawiera szeregi dzienne w pełnej szczegółowości za ostatnie trzy lata, a wcześniej rozrzedza je do tygodniowych. Pięć szeregów, które FRED oznacza jako wymagające zgody właściciela, nigdy nie jest publikowanych (dwa spready ICE BofA, indeks S&amp;P/Case-Shiller, S&amp;P 500 i NASDAQ Composite). Zastępują je ceny domów FHFA oraz spready Moody's Baa i Aaa, a sygnał z rynku akcji niesie VIX. Pięć szeregów pomocniczych pobiera się do łączenia i mianowników, ale ich nie pokazuje (IOER, dzienna stopa fed funds, pojedynczy cel stopy sprzed 2008 r., liczba bezrobotnych i PKB nominalny), do tego GS10 i TB3MS do modelu krzywej rentowności.</p>`)
       :T(`<p>The data come from Eurostat (the JSON-stat API: national accounts, short-term business statistics, HICP, labour force survey, business and consumer surveys, government finance, exchange rates), Statistics Poland's API DBW (first-release industrial production, retail sales, CPI, enterprise employment and wages, registered unemployment, business climate and consumer confidence), Narodowy Bank Polski (exchange rates through its Web API; money, loans, deposits, lending rates, core inflation and enterprise inflation expectations from its workbooks), the Ministry of Finance (State Treasury debt and the non-resident holdings of Treasury securities), the Bank for International Settlements (policy rate, credit aggregates and gap, property prices, effective exchange rate), the ECB (the non-performing loans ratio from the consolidated banking data), the OECD (composite business and consumer confidence), the Warsaw Stock Exchange (the WIG index) and YieldCartography's own daily Polish treasury curve (fitted yields, slopes, term premium, spread to the euro-area curve, liquidity composite, realised volatility).</p>
<p>The YieldCartography pipeline refreshes the store every weekday after the 11:00 Warsaw releases, re-reading a revision window at each source, and rebuilds one JSON file (schema <code>macro_radar/v1</code>, country PL) with the same publish guard as the US file. This page reads it from macrocartography.com/data/pl.json; the older address yieldcartography.com/data/macro/macro_radar_pl.json still answers. The file keeps daily series at full detail for the last three years and thins them to weekly before that. Rows of the registry without data are listed as not published.</p>`,
          `<p>Dane pochodzą z Eurostatu (API JSON-stat: rachunki narodowe, krótkookresowe statystyki działalności, HICP, badanie aktywności ekonomicznej ludności, badania koniunktury i nastrojów konsumentów, finanse publiczne, kursy walut), z API DBW Głównego Urzędu Statystycznego (pierwsze odczyty produkcji przemysłowej, sprzedaży detalicznej, CPI, zatrudnienia i wynagrodzeń w przedsiębiorstwach, bezrobocia rejestrowanego, koniunktury i nastrojów konsumentów), z Narodowego Banku Polskiego (kursy walut przez Web API; pieniądz, kredyty, depozyty, oprocentowanie, inflacja bazowa i oczekiwania inflacyjne przedsiębiorstw z jego arkuszy), z Ministerstwa Finansów (dług Skarbu Państwa i skarbowe papiery wartościowe w posiadaniu nierezydentów), z Banku Rozrachunków Międzynarodowych (stopa polityki, agregaty i luka kredytowa, ceny nieruchomości, efektywny kurs walutowy), z EBC (wskaźnik kredytów zagrożonych ze skonsolidowanych danych bankowych), z OECD (złożone wskaźniki koniunktury firm i konsumentów), z Giełdy Papierów Wartościowych w Warszawie (indeks WIG) oraz z własnej dziennej krzywej polskich obligacji skarbowych YieldCartography (dopasowane rentowności, nachylenia, premia za termin, spread do krzywej strefy euro, złożona miara płynności, zrealizowana zmienność).</p>
<p>Proces YieldCartography odświeża zbiór w każdy dzień roboczy po publikacjach o 11:00 czasu warszawskiego, ponownie czytając okno rewizji w każdym źródle, i buduje jeden plik JSON (schemat <code>macro_radar/v1</code>, kraj PL) z tym samym zabezpieczeniem publikacji co plik amerykański. Ta strona czyta go z macrocartography.com/data/pl.json; dawny adres yieldcartography.com/data/macro/macro_radar_pl.json nadal działa. Plik zawiera szeregi dzienne w pełnej szczegółowości za ostatnie trzy lata, a wcześniej rozrzedza je do tygodniowych. Wiersze rejestru bez danych są wymienione jako niepublikowane.</p>`))
    +T(`<p>On opening, this page asks for the live file and accepts it only if it parses as JSON, carries the schema tag, its internal counts match its content, it has scores whenever the saved copy has them, and it is not older than the saved copy. Otherwise it shows the copy saved inside the HTML file, with the reason in the amber status line.</p>`,
       `<p>Po otwarciu strona pobiera plik bieżący i przyjmuje go tylko wtedy, gdy jest poprawnym JSON-em, ma znacznik schematu, jego wewnętrzne liczniki zgadzają się z zawartością, ma wyniki zawsze wtedy, gdy ma je zapisana kopia, i nie jest starszy od zapisanej kopii. W przeciwnym razie pokazuje kopię zapisaną w pliku HTML, a powód podaje w bursztynowym pasku stanu.</p>`)];
  // 3
  S[3]=[T("Transforms","Przekształcenia"),
    T(`<p>Each series is first turned into the quantity that is scored, x. The transform for each series is listed in the catalogue (section 16). Transforms in use: ${tfList}.</p>`,`<p>Każdy szereg najpierw zamienia się na wielkość, która jest oceniana, x. Przekształcenie każdego szeregu podaje katalog (punkt 16). Używane przekształcenia: ${tfList}.</p>`)
    +tfTable
    +(US?T(`<p>Splices for scoring only: interest on reserve balances is extended back with IOER before 2021-07-29, the effective federal funds rate with the daily federal funds rate before 2000-07-03, and the upper and lower target range with the single target rate before 2008-12-16. One derived series, the mortgage spread D_MTGSPREAD, is MORTGAGE30US minus DGS10.</p>`,
            `<p>Łączenia wyłącznie na potrzeby oceny: oprocentowanie rezerw jest przedłużane wstecz przez IOER przed 2021-07-29, efektywna stopa fed funds przez dzienną stopę fed funds przed 2000-07-03, a górna i dolna granica celu przez pojedynczy cel stopy przed 2008-12-16. Jeden szereg pochodny, spread hipoteczny D_MTGSPREAD, to MORTGAGE30US minus DGS10.</p>`)
        :T(`<p>Derived series: the real policy stance is WIBOR 3M minus core HICP y/y, the EUR/PLN realised volatility is computed from the NBP fixings, and the non-resident share of domestic marketable Treasury securities is 100 &times; holdings of non-residents / securities outstanding, scored as its 12-month change. GUS indices published with the previous year = 100 are scored minus 100.</p>`,
           `<p>Szeregi pochodne: realne nastawienie polityki to WIBOR 3M minus bazowy HICP r/r, zrealizowana zmienność EUR/PLN jest liczona z fixingów NBP, a udział nierezydentów w krajowych rynkowych skarbowych papierach wartościowych to 100 &times; papiery w posiadaniu nierezydentów / papiery w obrocie, oceniany jako jego zmiana 12-miesięczna. Indeksy GUS publikowane z rokiem poprzednim = 100 są oceniane po odjęciu 100.</p>`))];
  // 4
  S[4]=[T("Indicator statistics","Statystyki wskaźników"),
    `<span class="eq">z<sub>t</sub> = (x<sub>t</sub> &minus; ${T("median","mediana")}<sub>W</sub>) / (1.4826 &middot; MAD<sub>W</sub>)</span>`
    +T(`<p>W is the window of observations dated within the last 3,653 days (10 years) up to and including t. Before a series has 10 years of history the window expands, and no z is computed before 1,826 days (5 years). The factor 1.4826 makes the median absolute deviation comparable to a standard deviation for normal data, so that one extreme episode such as 2020 does not inflate the scale for the next decade. Where the MAD is zero (step series such as the policy target range) the window's standard deviation is used.</p>
<p>Other readouts: <b>percentile</b> is the share of all x observations${CP.pctSince?" since "+CP.pctSince:" in the stored history"} at or below the latest x. <b>Momentum</b> is x now minus x 3 months (and 12 months) earlier. <b>Surprise</b> is the latest x minus the average of the previous 6 observations (20 for daily series), divided by the same robust scale. <b>Accelerating</b> means the latest 3-month change is larger than the 3-month change before it.</p>`,
       `<p>W to okno obserwacji z ostatnich 3653 dni (10 lat) do t włącznie. Zanim szereg ma 10 lat historii, okno się rozszerza, a przed upływem 1826 dni (5 lat) nie liczy się z. Współczynnik 1.4826 sprawia, że mediana odchyleń bezwzględnych (MAD) jest porównywalna z odchyleniem standardowym dla danych normalnych, więc jeden skrajny epizod, taki jak 2020 r., nie rozdyma skali na następną dekadę. Gdy MAD wynosi zero (szeregi schodkowe, np. przedział celu stopy), używa się odchylenia standardowego okna.</p>
<p>Inne odczyty: <b>centyl</b> to udział wszystkich obserwacji x${CP.pctSince?" od "+CP.pctSince+" r.":" w przechowywanej historii"} na poziomie ostatniego x lub poniżej. <b>Dynamika</b> to x teraz minus x 3 miesiące (i 12 miesięcy) wcześniej. <b>Niespodzianka</b> to ostatnie x minus średnia 6 poprzednich obserwacji (20 dla szeregów dziennych), podzielone przez tę samą odporną skalę. <b>Przyspieszenie</b> oznacza, że ostatnia zmiana 3-miesięczna jest większa od poprzedniej zmiany 3-miesięcznej.</p>`)];
  // 5
  S[5]=[T("Monthly grid and carry-forward","Siatka miesięczna i przenoszenie"),
    T(`<p>All scores live on a monthly grid that starts in ${US?"January 1975 (scores from 1980)":"January 2000"}. An indicator's value in a month is its last observation in that month, carried forward while it is not too old: daily and weekly series 1 month, monthly series 3 months, quarterly series 3 months after the end of the quarter, annual series 12 months after the end of the year. After that the indicator drops out of its group until it prints again.</p>`,
      `<p>Wszystkie wyniki leżą na siatce miesięcznej, która zaczyna się ${US?"w styczniu 1975 r. (wyniki od 1980 r.)":"w styczniu 2000 r."}. Wartość wskaźnika w danym miesiącu to jego ostatnia obserwacja w tym miesiącu, przenoszona, dopóki nie jest zbyt stara: szeregi dzienne i tygodniowe 1 miesiąc, miesięczne 3 miesiące, kwartalne 3 miesiące po końcu kwartału, roczne 12 miesięcy po końcu roku. Potem wskaźnik wypada ze swojej grupy, dopóki nie pojawi się nowy odczyt.</p>`)];
  // 6
  S[6]=[T("Group dials","Tarcze grup"),
    `<span class="eq">s<sub>i,t</sub> = ${T("polarity","kierunek")}<sub>i</sub> &middot; min(max(z<sub>i,t</sub>, &minus;3), 3)</span>`
    +`<span class="eq">Z<sub>g,t</sub> = ${T("weighted mean of s<sub>i,t</sub> over the members of group g with a reading in month t (at least 3, or all if fewer)","średnia ważona s<sub>i,t</sub> po członkach grupy g z odczytem w miesiącu t (co najmniej 3 albo wszyscy, jeśli jest ich mniej)")}</span>`
    +`<span class="eq">${T("dial","tarcza")}<sub>g,t</sub> = 100 &middot; &Phi;(Z<sub>g,t</sub>)</span>`
    +T(`<p>Polarity is +1 when a higher value reads stronger (or, for policy, tighter) and &minus;1 otherwise. The engine weights members equally. On the dashboard each group dial is read in the direction of the headline it feeds: inflation as price pressure, credit as tightness and markets as stress are shown as 100 minus the engine dial.</p>`,
       `<p>Kierunek wynosi +1, gdy wyższa wartość oznacza siłę (lub, dla polityki, zacieśnienie), a &minus;1 w przeciwnym razie. Silnik waży członków jednakowo. Na pulpicie każda tarcza grupy jest czytana w kierunku wskaźnika głównego, do którego trafia: inflacja jako presja cenowa, kredyt jako restrykcyjność, a rynki jako napięcie są pokazane jako 100 minus tarcza silnika.</p>`)];
  // 7
  S[7]=[T("Headline gauges","Wskaźniki główne"),
    `<span class="eq">${T("headline","wskaźnik")}<sub>t</sub> = 100 &middot; &Phi;( &Sigma;<sub>g</sub> w<sub>g</sub> &middot; ${T("sign","znak")}<sub>g</sub> &middot; Z<sub>g,t</sub> ), &nbsp;&nbsp; &Sigma;<sub>g</sub> w<sub>g</sub> = 1</span>`
    +T(`<p>Economy uses output, labor, consumer and housing. Policy stance combines the monetary policy group (default weight 75%) with fiscal impulse (25%, see section 8); the published engine file still holds the monetary-only gauge, and this page recomputes the blend. If fiscal impulse has no reading in a month (before its 5-year history is complete, or more than 3 months after the last print), the monetary group carries the gauge alone.${US?"":" In the Polish file the general government balance itself is also a member of the policy group, so the fiscal position enters twice: as a level there and as a change here."} Financial conditions use credit and markets with the sign reversed, so a high reading means tight. Price pressure uses the inflation group with the sign reversed, so a high reading means high pressure. A headline needs all its groups in the month. Weights in effect on this page:<br>${wtxt}</p>
<p>Contributions (Radar, selected gauge): each indicator contributes w<sub>g</sub> &times; (its weight in the group) &times; its score read in the gauge's direction. The contributions add up to the gauge's z. Gauge points are approximated as contribution &times; 100 &middot; &phi;(z), the slope of the dial at the current reading. Movers are the three largest changes in contribution over 3 months.</p>`,
       `<p>Gospodarka korzysta z produkcji, rynku pracy, konsumpcji i mieszkalnictwa. Nastawienie polityki łączy grupę polityki pieniężnej (domyślna waga 75%) z impulsem fiskalnym (25%, zob. punkt 8); opublikowany plik silnika zawiera wskaźnik tylko pieniężny, a ta strona przelicza połączenie. Gdy impuls fiskalny nie ma odczytu w danym miesiącu (zanim uzbiera 5 lat historii albo ponad 3 miesiące po ostatnim odczycie), wskaźnik niesie sama grupa pieniężna.${US?"":" W polskim pliku sam wynik sektora instytucji rządowych i samorządowych jest też członkiem grupy polityki, więc pozycja fiskalna wchodzi dwa razy: jako poziom tam i jako zmiana tutaj."} Warunki finansowe korzystają z kredytu i rynków ze znakiem odwróconym, więc wysoki odczyt oznacza restrykcyjność. Presja cenowa korzysta z grupy inflacji ze znakiem odwróconym, więc wysoki odczyt oznacza wysoką presję. Wskaźnik główny potrzebuje wszystkich swoich grup w danym miesiącu. Wagi obowiązujące na tej stronie:<br>${wtxt}</p>
<p>Wkłady (Radar, wybrany wskaźnik): każdy składnik wnosi w<sub>g</sub> &times; (swoją wagę w grupie) &times; swój wynik czytany w kierunku wskaźnika. Wkłady sumują się do z wskaźnika. Punkty wskaźnika przybliża się jako wkład &times; 100 &middot; &phi;(z), czyli nachylenie tarczy przy bieżącym odczycie. Największe zmiany to trzy największe zmiany wkładu w ciągu 3 miesięcy.</p>`)];
  // 8
  S[8]=[T("Fiscal impulse","Impuls fiskalny"),
    (US?`<span class="eq">${T("impulse","impuls")}<sub>t</sub> = &minus;( D<sub>t</sub> &minus; D<sub>t&minus;12</sub> ), &nbsp;&nbsp; D<sub>t</sub> = ${T("12-month sum of the federal surplus or deficit (MTSDS133FMS) as % of GDP","12-miesięczna suma nadwyżki lub deficytu federalnego (MTSDS133FMS) w % PKB")}</span>`
       :`<span class="eq">${T("impulse","impuls")}<sub>t</sub> = &minus;( B<sub>q</sub> &minus; B<sub>q&minus;4</sub> ), &nbsp;&nbsp; B<sub>q</sub> = ${T("general government net lending (+) / borrowing (&minus;), % of GDP, quarterly, seasonally and calendar adjusted (Eurostat, PL_GG_BAL)","wynik sektora instytucji rządowych i samorządowych, nadwyżka (+) / deficyt (&minus;), % PKB, kwartalnie, wyrównany sezonowo i o dni robocze (Eurostat, PL_GG_BAL)")}</span>`)
    +T(`<p>Below zero the deficit is shrinking, a drag on demand. Above zero it is widening, a stimulus. It is shown in percentage points of GDP, not as a 0 to 100 dial.</p>`,`<p>Poniżej zera deficyt maleje, co hamuje popyt. Powyżej zera rośnie, co jest bodźcem. Pokazuje się go w punktach procentowych PKB, a nie jako tarczę od 0 do 100.</p>`)
    +`<span class="eq">Z<sub>F,t</sub> = clip( &minus;(${T("impulse","impuls")}<sub>t</sub> &minus; ${T("median","mediana")}) / (1.4826 &middot; MAD), &plusmn;3 ), &nbsp;&nbsp; ${T("rolling 120 months, at least 60","kroczące 120 miesięcy, co najmniej 60")}</span>`
    +T(`<p>As a part of the policy stance, the impulse is scored like every indicator (robust z over a rolling 10-year window) with the sign reversed, so fiscal tightening reads as tighter policy. It is carried forward up to 3 months after its last print and enters the policy stance with weight 25% by default (Assumptions tab). Its own readout line in the Policy stance card stays in pp of GDP.</p>`,
       `<p>Jako część nastawienia polityki impuls jest oceniany jak każdy wskaźnik (odporny z w kroczącym oknie 10-letnim) ze znakiem odwróconym, więc zacieśnienie fiskalne oznacza bardziej restrykcyjną politykę. Jest przenoszony do 3 miesięcy po ostatnim odczycie i wchodzi do nastawienia polityki domyślnie z wagą 25% (zakładka Założenia). Jego własna linia w karcie Nastawienie polityki pozostaje w punktach procentowych PKB.</p>`)];
  // 9
  S[9]=[T("Regime compass","Kompas reżimów"),
    T(`<p>Each month is placed at x = the economy gauge's z and y = the price-pressure gauge's z. The quadrants are Overheating (growth above, prices above), Stagflation (growth below, prices above), Slowdown (both below) and Goldilocks (growth above, prices below), split at the cut-offs on the Assumptions tab (0 and 0 by default). The needle length is min(1, distance / 2) of the hole's radius, so the inner circle marks a distance of 1 and the rim 2 or more. The shares count months since ${y0}; the faint trail shows the twelve months before the latest.</p>`,
      `<p>Każdy miesiąc umieszcza się w punkcie x = z wskaźnika gospodarki i y = z wskaźnika presji cenowej. Ćwiartki to Przegrzanie (wzrost powyżej, ceny powyżej), Stagflacja (wzrost poniżej, ceny powyżej), Spowolnienie (oba poniżej) i Złoty środek (wzrost powyżej, ceny poniżej), rozdzielone progami z zakładki Założenia (domyślnie 0 i 0). Długość wskazówki to min(1, odległość / 2) promienia otworu, więc wewnętrzny okrąg oznacza odległość 1, a obrzeże 2 lub więcej. Udziały liczą miesiące od ${y0} r.; blady ślad pokazuje dwanaście miesięcy przed ostatnim.</p>`)];
  // 10
  S[10]=[T("Recession risk","Ryzyko recesji"),
    (US?T(`<p>The composite combines three published probabilities, each carried forward until its next print: the Chauvet and Piger smoothed recession probability (RECPROUSM156N, monthly, carried up to 3 months), Hamilton's GDP-based recession indicator (JHGDPBRINDX, quarterly, carried up to 9 months because it is published with a lag), and the New York Fed yield-curve model (12 months ahead, carried up to 3 months). The engine default is their simple average with at least two parts present. Current setting: ${recSet}.</p>
<span class="eq">P(recession in t+12) = &Phi;( &minus;0.5333 &minus; 0.6330 &middot; spread<sub>t</sub> )</span>
<p>spread = GS10 minus the 3-month bill on a bond-equivalent basis, BEY = 100 &middot; 365 &middot; d / (360 &minus; 91 &middot; d) with d the TB3MS discount rate as a fraction, monthly averages. The coefficients were recovered from the New York Fed's own monthly file and reproduce its published probabilities.</p>
<p>The Sahm rule (SAHMREALTIME) is shown as a flag and is never averaged, because it is not a probability. The rule's own trigger is 0.50. The quiet and rising bands under 0.50 are a dashboard choice.</p>
<p>The parts mix timing: Piger and Hamilton describe the current month or quarter, the yield-curve model a recession 12 months ahead.</p>`,
      `<p>Indeks złożony łączy trzy publikowane prawdopodobieństwa, każde przenoszone do następnego odczytu: wygładzone prawdopodobieństwo recesji Chauveta i Pigera (RECPROUSM156N, miesięczne, przenoszone do 3 miesięcy), wskaźnik recesji Hamiltona oparty na PKB (JHGDPBRINDX, kwartalny, przenoszony do 9 miesięcy, bo publikuje się go z opóźnieniem) oraz model krzywej rentowności Fed z Nowego Jorku (12 miesięcy naprzód, przenoszony do 3 miesięcy). Domyślnie silnik bierze ich zwykłą średnią przy co najmniej dwóch dostępnych składowych. Bieżące ustawienie: ${recSet}.</p>
<span class="eq">P(recesja w t+12) = &Phi;( &minus;0.5333 &minus; 0.6330 &middot; spread<sub>t</sub> )</span>
<p>spread = GS10 minus 3-miesięczny bon w ujęciu ekwiwalentu obligacji, BEY = 100 &middot; 365 &middot; d / (360 &minus; 91 &middot; d), gdzie d to stopa dyskontowa TB3MS jako ułamek, średnie miesięczne. Współczynniki odtworzono z miesięcznego pliku Fed z Nowego Jorku; odtwarzają jego publikowane prawdopodobieństwa.</p>
<p>Reguła Sahm (SAHMREALTIME) jest pokazywana jako flaga i nigdy nie jest uśredniana, bo nie jest prawdopodobieństwem. Próg samej reguły to 0.50. Pasma spokoju i wzrostu poniżej 0.50 są wyborem pulpitu.</p>
<p>Składowe różnią się horyzontem: Piger i Hamilton opisują bieżący miesiąc lub kwartał, a model krzywej recesję za 12 miesięcy.</p>`)
       :T(`<p>Poland has no official recession dating and no counterpart of the Chauvet and Piger or Hamilton probabilities, so the recession reading is a yield-curve probit alone: the New York Fed model applied to the Polish curve (POLGB 10-year yield minus WIBOR 3M), 12 months ahead, carried up to 3 months. It is indicative: the coefficients were estimated on US data, so read its direction rather than its level. Current setting: ${recSet}.</p>
<span class="eq">P(recession in t+12) = &Phi;( &minus;0.5333 &minus; 0.6330 &middot; spread<sub>t</sub> )</span>
<p>The Sahm rule is computed on the Eurostat LFS unemployment rate (seasonally adjusted) and shown as a flag; it is never averaged, because it is not a probability. The rule's own trigger is 0.50. The quiet and rising bands under 0.50 are a dashboard choice. The recession block of the registry also carries the OECD business confidence and the GUS synthetic business tendency indicator, published but not combined.</p>`,
          `<p>Polska nie ma oficjalnego datowania recesji ani odpowiednika prawdopodobieństw Chauveta i Pigera czy Hamiltona, więc odczyt recesji to sam probit krzywej rentowności: model Fed z Nowego Jorku zastosowany do polskiej krzywej (rentowność 10-letnich POLGB minus WIBOR 3M), 12 miesięcy naprzód, przenoszony do 3 miesięcy. Jest orientacyjny: współczynniki oszacowano na danych amerykańskich, więc ważniejszy jest jego kierunek niż poziom. Bieżące ustawienie: ${recSet}.</p>
<span class="eq">P(recesja w t+12) = &Phi;( &minus;0.5333 &minus; 0.6330 &middot; spread<sub>t</sub> )</span>
<p>Reguła Sahm jest liczona na stopie bezrobocia BAEL z Eurostatu (wyrównanej sezonowo) i pokazywana jako flaga; nigdy nie jest uśredniana, bo nie jest prawdopodobieństwem. Próg samej reguły to 0.50. Pasma spokoju i wzrostu poniżej 0.50 są wyborem pulpitu. Blok recesji w rejestrze zawiera też wskaźnik koniunktury OECD i syntetyczny wskaźnik koniunktury GUS, publikowane, ale nie łączone.</p>`))];
  // 11
  S[11]=[T("Zones and colours","Strefy i kolory"),
    T(`<p>Zones only colour and name the readings, they do not change any value. Cut-offs in effect on this page (editable on the Assumptions tab):</p>`,`<p>Strefy jedynie barwią i nazywają odczyty, nie zmieniają żadnej wartości. Progi obowiązujące na tej stronie (do zmiany w zakładce Założenia):</p>`)
    +`<table class="res">${cuts}</table>`
    +T(`<p>The recession-risk ring is stretched so its three zones get equal arcs. The cut-offs for every dial except the Sahm rule's 0.50 trigger are dashboard choices, not published thresholds.</p>`,`<p>Skala ryzyka recesji jest rozciągnięta tak, by jej trzy strefy miały równe łuki. Progi wszystkich tarcz poza progiem 0.50 reguły Sahm są wyborem pulpitu, a nie publikowanymi wartościami.</p>`)];
  // 12
  S[12]=[T("Reading the figures","Jak czytać wykresy"),
    T(`<ul>
<li><b>Gauge zones</b> show the share of months since ${y0} spent in each zone. The grey arc outside the ring marks the current zone.</li>
<li><b>Black needle</b>: the latest month. <b>Dashed needle</b>: ${mo(gh)} earlier. <b>Blue bowed arrow</b>: the move over the last ${mo(ar)} (both set on the Assumptions tab, both 3 months by default), from where the needle was to where it is. Moves under 22 degrees of arc are drawn at that minimum length so the direction stays visible. No change shows as a small blue ring.</li>
<li><b>Strips and heat maps</b> colour each month by the zone its reading fell in, using the same colours as the dial.</li>
<li><b>Member heat maps</b> colour each indicator by the zone its own score would give, 100 &times; &Phi;(score).</li>
<li><b>Green and red numbers</b> in tables read in the direction of the gauge or dial: green is stronger (for policy, tighter), red is weaker or more stress.</li>
${US?"<li><b>Grey bands</b> on time-series charts are NBER recessions (USREC).</li>":"<li>Time-series charts carry <b>no recession shading</b>: Poland has no official recession dating.</li>"}
<li><b>Standing charts</b> show the engine's robust z with bands at &plusmn;1 and &plusmn;2, capped at &plusmn;6 for display.</li>
<li><b>Figure tools</b>: &#10530; opens the figure large, CSV and XLS download its data, PNG saves it as an image with its title on top.</li>
</ul>`,
      `<ul>
<li><b>Strefy wskaźników</b> pokazują udział miesięcy od ${y0} r. spędzonych w każdej strefie. Szary łuk na zewnątrz skali oznacza bieżącą strefę.</li>
<li><b>Czarna wskazówka</b>: ostatni miesiąc. <b>Przerywana wskazówka</b>: ${mo(gh)} wcześniej. <b>Niebieska wygięta strzałka</b>: zmiana w ciągu ostatnich ${PLL?`${ar} ${plN(ar,"miesiąca","miesięcy","miesięcy")}`:mo(ar)} (oba ustawienia w zakładce Założenia, domyślnie po 3 miesiące), od miejsca, w którym była wskazówka, do miejsca, w którym jest. Ruchy poniżej 22 stopni łuku są rysowane w tej minimalnej długości, aby kierunek był widoczny. Brak zmiany to mały niebieski pierścień.</li>
<li><b>Paski i mapy cieplne</b> barwią każdy miesiąc kolorem strefy, w którą wpadł odczyt, tymi samymi kolorami co tarcza.</li>
<li><b>Mapy cieplne członków</b> barwią każdy wskaźnik kolorem strefy, jaką dałby jego własny wynik, 100 &times; &Phi;(wynik).</li>
<li><b>Zielone i czerwone liczby</b> w tabelach czyta się w kierunku wskaźnika lub tarczy: zielony to siła (dla polityki: zacieśnienie), czerwony to słabość lub większe napięcie.</li>
${US?"<li><b>Szare pasma</b> na wykresach czasowych to recesje według NBER (USREC).</li>":"<li>Wykresy czasowe <b>nie mają cieniowania recesji</b>: Polska nie ma oficjalnego datowania recesji.</li>"}
<li><b>Wykresy pozycji</b> pokazują odporny z silnika z pasmami &plusmn;1 i &plusmn;2, ograniczony do &plusmn;6 na potrzeby rysunku.</li>
<li><b>Narzędzia wykresów</b>: &#10530; otwiera wykres w dużym oknie, CSV i XLS pobierają jego dane, PNG zapisuje go jako obraz z tytułem u góry.</li>
</ul>`)];
  // 13
  S[13]=[T("Data health","Stan danych"),
    T(`<p>For each series the pipeline learns how long after a period ends its print first appears (the largest of the last 6 observed lags), and expects the next print by the end of the next period plus that lag plus a grace of 4 days (daily), 7 (weekly), 10 (monthly), 20 (quarterly) or 45 (annual). A series is <b>overdue</b> after that date, <b>stopped</b> when overdue by more than two full cycles, and <b>failed</b> when the last download failed (it keeps its old data). Discontinued helper series that are kept on purpose stay ok.${US?"":" Sources with long publication lags carry a longer expectation (the Ministry of Finance about 95 days, the ECB banking data about 200)."}</p>`,
      `<p>Dla każdego szeregu proces uczy się, jak długo po końcu okresu pojawia się pierwszy odczyt (największe z 6 ostatnich zaobserwowanych opóźnień), i oczekuje kolejnego odczytu do końca następnego okresu plus to opóźnienie plus margines 4 dni (dzienne), 7 (tygodniowe), 10 (miesięczne), 20 (kwartalne) lub 45 (roczne). Szereg jest <b>opóźniony</b> po tej dacie, <b>wstrzymany</b>, gdy opóźnienie przekracza dwa pełne cykle, i <b>z błędem</b>, gdy ostatnie pobranie się nie powiodło (zachowuje wtedy stare dane). Celowo zachowane wycofane szeregi pomocnicze pozostają ok.${US?"":" Źródła o długim opóźnieniu publikacji mają dłuższe oczekiwanie (Ministerstwo Finansów około 95 dni, dane bankowe EBC około 200)."}</p>`)];
  // 14
  S[14]=[T("Validation","Walidacja"),
    (US?T(`<ul>
<li><b>Audit workbook</b> (YIELDS/macro_radar/out/macro_radar_audit.xlsx): the labor group rebuilt with live spreadsheet formulas (3,343 formulas, 0 errors) matches the engine's member z-scores and the group dial exactly.</li>
<li><b>Yield-curve model</b>: the computed probabilities match all 431 overlapping months of the New York Fed's published series.</li>
<li><b>In the browser</b>: group dials rebuilt from member z match the engine within 0.52 dial points over 2,960 group-months (the published z-scores are rounded to two decimals). Contributions add up to each gauge's z within 0.02.</li>
<li><b>Back-test since 1996</b> (current data vintage): the economy gauge averaged 8.4 in NBER recession months and 52.5 in expansions and fell below 30 before or at each of the 2001, 2008 and 2020 recessions, but also spent 27 months below 30 without a recession, mostly 2022 to 2025 when housing was weak. The recession composite averaged 49 in recession months and 8.5 in expansions, above 30 in 89% of recession months and in 4 expansion months.</li>
</ul>`,`<ul>
<li><b>Arkusz audytowy</b> (YIELDS/macro_radar/out/macro_radar_audit.xlsx): grupa rynku pracy odtworzona żywymi formułami arkusza (3343 formuły, 0 błędów) zgadza się dokładnie z wynikami z członków i tarczą grupy z silnika.</li>
<li><b>Model krzywej rentowności</b>: wyliczone prawdopodobieństwa zgadzają się we wszystkich 431 wspólnych miesiącach z publikowanym szeregiem Fed z Nowego Jorku.</li>
<li><b>W przeglądarce</b>: tarcze grup odtworzone z wyników z członków zgadzają się z silnikiem z dokładnością do 0.52 punktu tarczy w 2960 miesiącach grup (publikowane wyniki z są zaokrąglone do dwóch miejsc). Wkłady sumują się do z każdego wskaźnika z dokładnością do 0.02.</li>
<li><b>Test wsteczny od 1996 r.</b> (bieżący rocznik danych): wskaźnik gospodarki wynosił średnio 8.4 w miesiącach recesji według NBER i 52.5 w ekspansjach i spadał poniżej 30 przed każdą z recesji 2001, 2008 i 2020 r. lub w ich trakcie, ale spędził też 27 miesięcy poniżej 30 bez recesji, głównie w latach 2022-2025, gdy słabe było mieszkalnictwo. Indeks złożony recesji wynosił średnio 49 w miesiącach recesji i 8.5 w ekspansjach; powyżej 30 był w 89% miesięcy recesji i w 4 miesiącach ekspansji.</li>
</ul>`)
       :T(`<ul>
<li><b>Same statistics code</b>: pl_build.py computes the transforms, robust z, group dials and headlines as the US chain does; its <code>--check</code> option validates against the US engine (macro_build.py) when it is present.</li>
<li><b>Checks against known figures</b> (from the data side's notes): HICP inflation of 17.2% y/y at its peak in February 2023, the NBP reference rate and WIBOR 3M against their published levels, the POLGB 2- and 10-year yields against the YieldCartography curve.</li>
<li><b>In the browser</b>: contributions add up to each gauge's z within 0.02, as for the US radar.</li>
<li>There is no back-test against recessions, because Poland has no official recession dating.</li>
</ul>`,`<ul>
<li><b>Ten sam kod statystyk</b>: pl_build.py liczy przekształcenia, odporny z, tarcze grup i wskaźniki główne tak jak łańcuch amerykański; jego opcja <code>--check</code> sprawdza zgodność z silnikiem amerykańskim (macro_build.py), gdy jest dostępny.</li>
<li><b>Porównanie ze znanymi wartościami</b> (z notatek części danych): szczyt inflacji HICP 17.2% r/r w lutym 2023 r., stopa referencyjna NBP i WIBOR 3M wobec ich publikowanych poziomów, rentowności 2- i 10-letnich POLGB wobec krzywej YieldCartography.</li>
<li><b>W przeglądarce</b>: wkłady sumują się do z każdego wskaźnika z dokładnością do 0.02, jak w radarze amerykańskim.</li>
<li>Nie ma testu wstecznego na recesjach, bo Polska nie ma oficjalnego datowania recesji.</li>
</ul>`))];
  // 15
  S[15]=[T("Limits","Ograniczenia"),
    T(`<ul>
<li>Back-tests use today's data vintage. Several series${US?", and the Piger and Hamilton probabilities in particular,":""} are revised or smoothed after the fact, so history reads better than it did in real time.</li>
<li>Daily and quarterly data share one monthly score through the carry-forward rule. This is not a mixed-frequency nowcast.</li>
<li>A single number invites over-reading. The member tables show what drives each dial.</li>
<li>Zone cut-offs are judgement, not published thresholds.</li>
<li>Changing the assumptions recomputes from rounded z-scores, so small differences from the engine are expected.</li>
${US?"":"<li>Some sources are read from workbooks rather than an API (NBP money and credit, the Ministry of Finance debt, core inflation, inflation expectations); a few of them are refreshed by hand, so they can lag more than the rest.</li><li>The recession reading borrows US coefficients and is indicative only.</li>"}
</ul>`,`<ul>
<li>Testy wsteczne korzystają z dzisiejszego rocznika danych. Część szeregów${US?", w szczególności prawdopodobieństwa Pigera i Hamiltona,":""} jest rewidowana lub wygładzana po fakcie, więc historia wygląda lepiej, niż wyglądała w czasie rzeczywistym.</li>
<li>Dane dzienne i kwartalne dzielą jeden wynik miesięczny dzięki regule przenoszenia. To nie jest nowcast o mieszanej częstotliwości.</li>
<li>Jedna liczba zachęca do nadinterpretacji. Tabele członków pokazują, co porusza każdą tarczą.</li>
<li>Progi stref są kwestią oceny, a nie publikowanymi wartościami.</li>
<li>Zmiana założeń przelicza wyniki z zaokrąglonych z, więc spodziewane są drobne różnice wobec silnika.</li>
${US?"":"<li>Część źródeł czyta się z arkuszy, a nie przez API (pieniądz i kredyt NBP, dług Ministerstwa Finansów, inflacja bazowa, oczekiwania inflacyjne); kilka z nich odświeża się ręcznie, więc mogą bardziej się opóźniać niż reszta.</li><li>Odczyt recesji pożycza amerykańskie współczynniki i jest wyłącznie orientacyjny.</li>"}
</ul>`)];
  // 16
  S[16]=[T("Series catalogue","Katalog szeregów"),
    (US?T(`<p>${nSer} published series. Rights follow each series' FRED page: public means public domain, cite means copyrighted with citation required. Each id links to its FRED page, and the full citation is on the Data health tab.</p>`,`<p>Publikowane szeregi: ${nSer}. Prawa wynikają ze strony każdego szeregu w FRED: public oznacza domenę publiczną, cite oznacza prawa autorskie z wymogiem cytowania. Każdy identyfikator prowadzi do strony w FRED, a pełne cytowanie jest w zakładce Stan danych.</p>`)
       :T(`<p>${nSer} published series. Rights follow each source's terms: public means reuse with attribution or own data, cite means terms of use with citation. Each id links to its source page, and the full citation is on the Data health tab.</p>`,`<p>Publikowane szeregi: ${nSer}. Prawa wynikają z warunków każdego źródła: public oznacza ponowne wykorzystanie z podaniem źródła albo dane własne, cite oznacza warunki korzystania z cytowaniem. Każdy identyfikator prowadzi do strony źródła, a pełne cytowanie jest w zakładce Stan danych.</p>`))
    +`<div class="data-wrap" style="max-height:60vh"><table class="res">${cat}</table></div>`];
  // 17
  S[17]=[T("Sources","Źródła"),
    (US?T(`<ul>
<li>FRED, Federal Reserve Bank of St. Louis, https://fred.stlouisfed.org/ (every series, retrieved through the fredgraph.csv endpoint). Each series' citation, as FRED recommends it, is on the Data health tab.</li>
<li>Federal Reserve Bank of New York, The Yield Curve as a Leading Indicator, and its monthly data file allmonth.xls (model coefficients).</li>
<li>Chauvet and Piger smoothed recession probabilities, FRED series RECPROUSM156N. Hamilton GDP-based recession indicator, FRED series JHGDPBRINDX. Sahm rule real-time indicator, FRED series SAHMREALTIME. NBER recession indicator, FRED series USREC.</li>
</ul>`,`<ul>
<li>FRED, Federal Reserve Bank of St. Louis, https://fred.stlouisfed.org/ (wszystkie szeregi, pobierane przez punkt fredgraph.csv). Cytowanie każdego szeregu w formie zalecanej przez FRED jest w zakładce Stan danych.</li>
<li>Federal Reserve Bank of New York, The Yield Curve as a Leading Indicator, wraz z miesięcznym plikiem danych allmonth.xls (współczynniki modelu).</li>
<li>Wygładzone prawdopodobieństwa recesji Chauveta i Pigera, szereg FRED RECPROUSM156N. Wskaźnik recesji Hamiltona oparty na PKB, szereg FRED JHGDPBRINDX. Reguła Sahm w czasie rzeczywistym, szereg FRED SAHMREALTIME. Wskaźnik recesji NBER, szereg FRED USREC.</li>
</ul>`)
       :T(`<ul>
<li>Eurostat, https://ec.europa.eu/eurostat (JSON-stat API; reuse with attribution).</li>
<li>Statistics Poland (GUS), API DBW, https://api-dbw.stat.gov.pl (CC BY 4.0).</li>
<li>Narodowy Bank Polski: Web API, https://api.nbp.pl (exchange rates), and the statistical workbooks on nbp.pl (money, loans, deposits, interest rates, core inflation, inflation expectations).</li>
<li>Ministry of Finance, State Treasury debt time series, https://www.gov.pl/web/finanse.</li>
<li>Bank for International Settlements, BIS Data Portal, https://data.bis.org (terms of use).</li>
<li>European Central Bank, ECB Data Portal, consolidated banking data (non-performing loans ratio).</li>
<li>OECD Data Explorer, https://data-explorer.oecd.org (terms of use).</li>
<li>Giełda Papierów Wartościowych w Warszawie, quotation archive (WIG index).</li>
<li>YieldCartography, https://yieldcartography.com (own computation of the Polish treasury curve, term premia, spreads and liquidity from BondSpot fixings).</li>
<li>Recession reading: yield-curve probit with the New York Fed coefficients (Federal Reserve Bank of New York, The Yield Curve as a Leading Indicator) applied to the Polish curve, indicative; Sahm rule computed on the Eurostat LFS unemployment rate (SA).</li>
</ul>`,`<ul>
<li>Eurostat, https://ec.europa.eu/eurostat (API JSON-stat; ponowne wykorzystanie z podaniem źródła).</li>
<li>Główny Urząd Statystyczny (GUS), API DBW, https://api-dbw.stat.gov.pl (CC BY 4.0).</li>
<li>Narodowy Bank Polski: Web API, https://api.nbp.pl (kursy walut), oraz arkusze statystyczne na nbp.pl (pieniądz, kredyty, depozyty, oprocentowanie, inflacja bazowa, oczekiwania inflacyjne).</li>
<li>Ministerstwo Finansów, szeregi czasowe długu Skarbu Państwa, https://www.gov.pl/web/finanse.</li>
<li>Bank Rozrachunków Międzynarodowych, BIS Data Portal, https://data.bis.org (warunki korzystania).</li>
<li>Europejski Bank Centralny, ECB Data Portal, skonsolidowane dane bankowe (wskaźnik kredytów zagrożonych).</li>
<li>OECD Data Explorer, https://data-explorer.oecd.org (warunki korzystania).</li>
<li>Giełda Papierów Wartościowych w Warszawie, archiwum notowań (indeks WIG).</li>
<li>YieldCartography, https://yieldcartography.com (własne wyliczenia krzywej polskich obligacji skarbowych, premii za termin, spreadów i płynności z fixingów BondSpot).</li>
<li>Odczyt recesji: probit krzywej rentowności ze współczynnikami Fed z Nowego Jorku (Federal Reserve Bank of New York, The Yield Curve as a Leading Indicator) zastosowany do polskiej krzywej, orientacyjny; reguła Sahm liczona na stopie bezrobocia BAEL z Eurostatu (sa).</li>
</ul>`))
    +T(`<p class="note">Method code: ${US?"macro_fetch.py, macro_score.py, macro_composite.py and macro_build.py in YIELDS/macro_radar":"the readers, derive.py and pl_build.py in FTP/macro_radar/pl"}. Dashboard: macro_radar_template_mc.html, one template for both radars and both languages.</p>`,
       `<p class="note">Kod metody: ${US?"macro_fetch.py, macro_score.py, macro_composite.py i macro_build.py w YIELDS/macro_radar":"czytniki, derive.py i pl_build.py w FTP/macro_radar/pl"}. Pulpit: macro_radar_template_mc.html, jeden szablon dla obu radarów i obu języków.</p>`)];
  const nums=Object.keys(S).map(Number).sort((a,b)=>a-b);
  box.innerHTML=`<h3>${T("Contents","Spis treści")}</h3>\n<p class="toc">${nums.map(n=>`${n} ${S[n][0]}`).join(" &middot; ")}</p>\n`
    +nums.map(n=>`\n<h3>${n}. ${S[n][0]}</h3>\n${S[n][1]}`).join("\n");
  box.setAttribute("data-notr","1");   // written in the viewer's language already
}
