// ---------------- Polish dictionary (English UI string -> Polish) ----------------
// Exact strings first (keys are the English text as it appears, whitespace collapsed), then pattern rules for text
// with numbers, then series names and units (labels_pl.js). Official source titles and citations are not translated.
const plN = (n, one, few, many) => { n=Math.abs(+String(n).replace(/[^\d.-]/g,"")); if(n===1) return one; const d=n%10, h=n%100; return (d>=2&&d<=4&&(h<12||h>14))?few:many; };
const PL_MON = {Jan:"sty",Feb:"lut",Mar:"mar",Apr:"kwi",May:"maj",Jun:"cze",Jul:"lip",Aug:"sie",Sep:"wrz",Oct:"paź",Nov:"lis",Dec:"gru"};
const PL_DICT = {
  // ---- header, tabs, buttons ----
  "Radar":"Radar", "History":"Historia", "Finder":"Wyszukiwarka", "Latest":"Najnowsze", "Data health":"Stan danych", "Assumptions":"Założenia", "Technical appendix":"Aneks techniczny",
  "details":"szczegóły", "☽ Dark":"☽ Ciemny", "☼ Light":"☼ Jasny", "💾 Save HTML snapshot":"💾 Zapisz migawkę HTML", "by MARCIN DEC":"autor: MARCIN DEC",
  "Off leaves only the Radar tab and hides Latest, Data health, Assumptions and the Technical appendix. Saved with the snapshot.":"Wyłączone zostawia zakładki Radar, Historia i Wyszukiwarka, a ukrywa Najnowsze, Stan danych, Założenia i Aneks techniczny. Zapisywane w migawce.",
  "Switch between light and dark mode (saved with the snapshot)":"Przełącz tryb jasny i ciemny (zapisywane w migawce)",
  "Download a self-contained copy of this dashboard with the data currently shown, the theme, the title, the subtitle and the instruction text baked in":"Pobierz samodzielną kopię pulpitu z pokazywanymi danymi, motywem, tytułem, podtytułem i tekstem instrukcji",
  "Where the numbers on this page come from. Green: today's published file. Amber: the copy saved inside this HTML file, because the live file could not be loaded or did not pass the checks.":"Skąd pochodzą liczby na tej stronie. Zielony: dzisiejszy opublikowany plik. Bursztynowy: kopia zapisana w tym pliku HTML, bo plik bieżący nie wczytał się albo nie przeszedł kontroli.",
  "Click to edit; saved with the HTML snapshot":"Kliknij, aby edytować; zapisywane w migawce HTML", "Expert tab, hidden when the details tickbox is off":"Zakładka ekspercka, ukryta po wyłączeniu pola szczegóły",
  "Loading data…":"Wczytywanie danych…", "Country data":"Dane kraju", "Language":"Język", "English":"English", "Polski":"Polski",
  "Showing data for {0}":"Dane: {0}", "Switch to the {0} radar":"Przełącz na radar: {0}", "United States":"Stany Zjednoczone", "Poland":"Polska",
  "Macro Radar · United States":"Macro Radar · Stany Zjednoczone", "Macro Radar · Poland":"Macro Radar · Polska",
  // ---- status line ----
  "Live data from {0}: ":"Dane bieżące z {0}: ", "data as of <b>{0}</b>, built {1}, {2} series":"dane na <b>{0}</b>, zbudowane {1}, szeregi: {2}",
  "series health: {0} ok":"stan szeregów: {0} ok", "{0} overdue":"{0} opóźnionych", "{0} stopped":"{0} wstrzymanych", "{0} failed":"{0} z błędem",
  "indicator scores not yet published":"wyniki wskaźników jeszcze nieopublikowane", "Showing {0}: ":"Pokazuję {0}: ", "the copy saved in this snapshot":"kopię zapisaną w tej migawce",
  "the demo data built into the template":"dane demonstracyjne wbudowane w szablon", "the copy saved in this file":"kopię zapisaną w tym pliku", "live file not used: ":"plik bieżący niewykorzystany: ",
  "No data: the live file could not be loaded":"Brak danych: nie udało się wczytać pliku bieżącego", " and this HTML file carries no saved copy.":", a ten plik HTML nie zawiera zapisanej kopii.",
  "the live file has no scores yet, the saved copy does":"plik bieżący nie ma jeszcze wyników, a zapisana kopia ma", "no address answered":"żaden adres nie odpowiedział", "network error (offline)":"błąd sieci (brak połączenia)",
  // ---- gauges, groups, zones ----
  "Economy":"Gospodarka", "Price pressure":"Presja cenowa", "Policy stance":"Nastawienie polityki", "Financial conditions":"Warunki finansowe", "Recession risk":"Ryzyko recesji",
  "Fiscal impulse":"Impuls fiskalny", "Monetary policy":"Polityka pieniężna", "Regime compass":"Kompas reżimów", "Sahm rule":"Reguła Sahm", "Composite":"Indeks złożony",
  "Overheating":"Przegrzanie", "Stagflation":"Stagflacja", "Slowdown":"Spowolnienie", "Goldilocks":"Złoty środek", "Group {0}":"Grupa {0}",
  "growth +":"wzrost +", "growth −":"wzrost −", "prices +":"ceny +", "prices −":"ceny −", "pp of GDP":"pkt proc. PKB", "pp of GDP, + = loosening":"pkt proc. PKB, + = luzowanie",
  "Parts of the gauge":"Składowe wskaźnika", "3-month movers":"Największe zmiany w 3 mies.", "(approx. gauge points):":"(przybliżone punkty wskaźnika):", "last 24 months":"ostatnie 24 miesiące",
  "Recession probabilities":"Prawdopodobieństwa recesji", "Output and production":"Produkcja", "Labor market":"Rynek pracy", "Consumer and income":"Konsumpcja i dochody",
  "Inflation and prices":"Inflacja i ceny", "Housing and real estate":"Mieszkalnictwo i nieruchomości", "Policy: monetary and fiscal":"Polityka: pieniężna i fiskalna",
  "Credit and banking":"Kredyt i banki", "Markets and financial stress":"Rynki i napięcia finansowe", "Recession block":"Blok recesji", "Output and activity":"Produkcja i aktywność",
  "Labour market":"Rynek pracy", "Consumer":"Konsumpcja", "Inflation":"Inflacja", "Housing and construction":"Mieszkalnictwo i budownictwo", "Policy, fiscal, external":"Polityka, finanse publiczne, sektor zewnętrzny",
  "Markets":"Rynki", "Markets:":"Rynki:", "Markets and financial stress:":"Rynki i napięcia finansowe:", "Fiscal impulse:":"Impuls fiskalny:",
  // ---- Radar hint, selections, detail frames ----
  "▼ Selected gauge":"▼ Wybrany wskaźnik", "▼ Selected group":"▼ Wybrana grupa", "× Close":"× Zamknij", "Close (Esc)":"Zamknij (Esc)",
  "Everything in this frame is about this gauge. Click another gauge to switch.":"Wszystko w tej ramce dotyczy tego wskaźnika. Kliknij inny wskaźnik, aby przełączyć.",
  "Click another dial to switch.":"Kliknij inną tarczę, aby przełączyć.", "Close this section and clear the selection (or click the selected dial again)":"Zamknij tę sekcję i wyczyść wybór (albo kliknij ponownie wybraną tarczę)",
  "Behind the gauge, last 24 months":"Za wskaźnikiem, ostatnie 24 miesiące", "Gauge and its groups, last 24 months":"Wskaźnik i jego grupy, ostatnie 24 miesiące",
  "Composite and its parts, last 24 months":"Indeks złożony i jego składowe, ostatnie 24 miesiące", "Fiscal impulse, last 24 months":"Impuls fiskalny, ostatnie 24 miesiące",
  "Top row: the gauge. Below: its groups, each read in the gauge's direction, in their own zone colours. The gauge is 100 × Φ of the weighted average of the group z-scores.":"Górny wiersz: wskaźnik. Poniżej: jego grupy, każda czytana w kierunku wskaźnika, we własnych kolorach stref. Wskaźnik to 100 × Φ ze średniej ważonej wyników z grup.",
  "Each part is carried forward until its next print, as in the composite. Sahm zones (quiet below 0.30, rising, triggered at 0.50) are mine; 0.50 is the rule's own trigger.":"Każda składowa jest przenoszona do następnego odczytu, jak w indeksie złożonym. Strefy reguły Sahm (spokój poniżej 0.30, wzrost, wyzwolona od 0.50) są wyborem pulpitu; 0.50 to próg samej reguły.",
  "Indicators behind the gauge":"Składniki wskaźnika", "Inputs to the composite":"Składowe indeksu złożonego", "Input series":"Szereg wejściowy",
  "Click a row to unfold its level, momentum and standing charts.":"Kliknij wiersz, aby rozwinąć wykresy poziomu, dynamiki i pozycji.",
  "Click a row to unfold its charts.":"Kliknij wiersz, aby rozwinąć jego wykresy.",
  "Gauge history":"Historia wskaźnika", "Group dial history":"Historia tarczy grupy", "Gauges and groups, last 24 months":"Wskaźniki i grupy, ostatnie 24 miesiące",
  "Member scores, last 24 months":"Wyniki członków, ostatnie 24 miesiące", "Members":"Członkowie", "In the gauge":"We wskaźniku", "flag only, not averaged":"tylko flaga, nieuśredniana",
  "not in the latest month (too old to carry)":"brak w ostatnim miesiącu (zbyt stary, by go przenieść)", "Sahm rule (flag)":"Reguła Sahm (flaga)",
  "3 probabilities averaged, Sahm rule as a flag":"3 prawdopodobieństwa uśrednione, reguła Sahm jako flaga", "Composite and its parts":"Indeks złożony i jego składowe",
  "percent; composite solid, parts dashed":"procent; indeks złożony linią ciągłą, składowe przerywaną", "gauge, 0-100":"wskaźnik, 0-100",
  "Policy stance (fiscal impulse)":"Nastawienie polityki (impuls fiskalny)", "fiscal impulse, robust z":"impuls fiskalny, odporny z",
  // ---- table headers and their tooltips ----
  "Id":"Id", "Series":"Szereg", "Group":"Grupa", "Kind":"Rodzaj", "Period":"Okres", "Value":"Wartość", "Scored as":"Oceniany jako", "Pctile":"Centyl", "Surprise":"Niespodzianka",
  "Last obs":"Ostatnia obs.", "Score":"Wynik", "Weight":"Waga", "Contribution":"Wkład", "≈ points":"≈ punkty", "3m chg":"zm. 3 mies.", "3m chg, pts":"zm. 3 mies., pkt", "Freq":"Częst.",
  "x":"x", "z":"z", "Polarity":"Kierunek", "Latest":"Najnowsze", "Gauge":"Wskaźnik", "Next due":"Następny odczyt", "Health":"Stan", "Rights":"Prawa", "Citation":"Cytowanie", "Source":"Źródło",
  "Click to unfold the charts":"Kliknij, aby rozwinąć wykresy", "new print, revision, or recent print":"nowy odczyt, rewizja lub niedawny odczyt", "Period of the latest observation":"Okres ostatniej obserwacji",
  "Latest value as published":"Ostatnia wartość, jak opublikowano", "Scoring transform of the latest value (for example y/y %)":"Przekształcenie oceniane dla ostatniej wartości (np. % r/r)",
  "Robust z of the scored value against the last 10 years":"Odporny z ocenianej wartości na tle ostatnich 10 lat",
  "Latest scored value minus the average of the previous six prints (twenty for daily), in robust z units. Colour: green = stronger or tighter policy, red = weaker or more stress":"Ostatnia oceniana wartość minus średnia sześciu poprzednich odczytów (dwudziestu dla dziennych), w jednostkach odpornego z. Kolor: zielony = silniej lub bardziej restrykcyjna polityka, czerwony = słabiej lub większe napięcie",
  "Short label used on this dashboard":"Krótka nazwa używana na pulpicie", "Dashboard group":"Grupa pulpitu", "Native frequency":"Częstotliwość źródłowa", "Date by which the next print is due":"Data, do której powinien pojawić się kolejny odczyt",
  "ok, overdue, stopped or failed":"ok, opóźniony, wstrzymany lub błąd", "Latest observation date":"Data ostatniej obserwacji", "Latest value":"Ostatnia wartość", "How it enters the gauge":"Jak wchodzi do wskaźnika",
  "Latest observation":"Ostatnia obserwacja", "Scoring transform":"Przekształcenie oceniane", "Latest scored value":"Ostatnia oceniana wartość", "Robust z against the last 10 years, before the polarity sign":"Odporny z na tle ostatnich 10 lat, przed znakiem kierunku",
  "+1: a higher value reads stronger (or tighter, for policy); -1: the reverse":"+1: wyższa wartość oznacza siłę (lub zacieśnienie w polityce); -1: odwrotnie",
  "Contribution to this group dial: z signed by polarity and the dial direction, clipped at ±3, on the latest month":"Wkład do tarczy grupy: z ze znakiem kierunku wskaźnika i tarczy, obcięty do ±3, w ostatnim miesiącu",
  "x now minus x three months earlier":"x teraz minus x trzy miesiące wcześniej", "Latest x minus the average of the previous six prints (twenty for daily), in robust z units":"Ostatnie x minus średnia sześciu poprzednich odczytów (dwudziestu dla dziennych), w jednostkach odpornego z",
  "Headline gauge the indicator feeds":"Wskaźnik główny, do którego trafia składnik", "z signed by polarity and the gauge direction, clipped at ±3, latest month":"z ze znakiem kierunku wskaźnika i wskaźnika głównego, obcięty do ±3, ostatni miesiąc",
  "Robust z signed to read like this gauge, clipped at ±3":"Odporny z ze znakiem jak w tym wskaźniku, obcięty do ±3", "Share of the gauge: headline weight of the group divided by the members with a reading":"Udział we wskaźniku: waga grupy podzielona przez członków z odczytem",
  "Score × weight, in z units of the gauge":"Wynik × waga, w jednostkach z wskaźnika", "Contribution × 100 φ(z) of the gauge: approximate gauge points":"Wkład × 100 φ(z) wskaźnika: przybliżone punkty wskaźnika",
  "Change in the contribution over the last 3 months, in approximate gauge points":"Zmiana wkładu w ostatnich 3 miesiącach, w przybliżonych punktach wskaźnika",
  "Share of the history since 1990 at or below the latest scored value":"Udział historii od 1990 r. na poziomie ostatniej ocenianej wartości lub poniżej", "Share of history since 1990 at or below the latest x":"Udział historii od 1990 r. na poziomie ostatniego x lub poniżej",
  "Share of the history at or below the latest scored value":"Udział historii na poziomie ostatniej ocenianej wartości lub poniżej", "Share of history at or below the latest x":"Udział historii na poziomie ostatniego x lub poniżej",
  // ---- unfolded rows ----
  "Level as published, 10 years":"Poziom, jak opublikowano, 10 lat", "Momentum: last 12 changes":"Dynamika: ostatnie 12 zmian", "Standing: robust z, 10 years":"Pozycja: odporny z, 10 lat",
  "scored as":"oceniany jako", "polarity":"kierunek", "daily":"dzienny", "weekly":"tygodniowy", "monthly":"miesięczny", "quarterly":"kwartalny", "annual":"roczny",
  "Open this figure large (Esc closes)":"Otwórz wykres w dużym oknie (Esc zamyka)", "Download the figure's data as CSV":"Pobierz dane wykresu jako CSV", "Download the figure's data as an Excel-readable table":"Pobierz dane wykresu jako tabelę dla Excela",
  "Download the figure as a PNG image at twice screen resolution":"Pobierz wykres jako obraz PNG w podwójnej rozdzielczości", "Download this table as CSV":"Pobierz tabelę jako CSV", "Download this table as an Excel-readable table":"Pobierz tabelę jako tabelę dla Excela",
  "▾ Open all":"▾ Rozwiń wszystkie", "▴ Close all":"▴ Zwiń wszystkie", "Unfold the charts of every row (can take a moment on long tables)":"Rozwiń wykresy każdego wiersza (w długich tabelach może to chwilę potrwać)", "Fold every row":"Zwiń wszystkie wiersze",
  "z signed to read like the dial, clipped at ±3":"z ze znakiem jak na tarczy, obcięty do ±3", "median":"mediana",
  // ---- History ----
  "Long series on the regime canvas":"Długie szeregi na tle reżimów", "Series and regimes":"Szeregi i reżimy", "The range by regime: months, mean and standard deviation of each series":"Zakres według reżimów: miesiące, średnia i odchylenie standardowe każdego szeregu",
  "History: long series on the regime canvas":"Historia: długie szeregi na tle reżimów", "right":"prawa oś", "(right)":"(prawa oś)", "add a series…":"dodaj szereg…", "default set":"zestaw domyślny", "range":"zakres", "whole history":"cała historia",
  "regime cut-offs":"progi reżimów", "growth z":"z wzrostu", "price z":"z cen", "no compass reading":"brak odczytu kompasu", "Regime":"Reżim", "Months":"Miesiące", "Share, %":"Udział, %", "mean":"średnia", "sd":"odch. std.",
  "No regime reading":"Brak odczytu reżimu", "All months in the range":"Wszystkie miesiące zakresu", "Draw on a right-hand axis (for series in other units)":"Rysuj na prawej osi (dla szeregów w innych jednostkach)", "Remove":"Usuń",
  "Shared with the Assumptions tab and the regime compass":"Wspólne z zakładką Założenia i kompasem reżimów", "Months of the range in this regime":"Miesiące zakresu w tym reżimie", "Monthly observations with data":"Obserwacje miesięczne z danymi",
  "Back to {0}":"Powrót do: {0}",
  // ---- Finder ----
  "Find indicators":"Znajdź wskaźniki", "All groups":"Wszystkie grupy", "Policy (monetary, and fiscal series)":"Polityka (pieniężna i szeregi fiskalne)", "scored only":"tylko oceniane",
  "Search":"Szukaj", "Show all":"Pokaż wszystkie", "Clear":"Wyczyść", "Results":"Wyniki", "display only":"tylko do wglądu", "In":"Uwzgl.", "to":"do", "In the dials":"W tarczach", "yes":"tak", "Nothing matches. Try fewer or shorter words, or Show all.":"Brak wyników. Spróbuj mniej lub krótszych słów albo Pokaż wszystkie.",
  // ---- Latest ----
  "What changed in the latest fetch":"Co zmieniło się w ostatnim pobraniu", "new":"nowy", "revised":"zrewidowany", "recent":"niedawny",
  "The latest pipeline run brought no new prints, so this shows the 25 most recent prints with the largest surprises instead.":"Ostatnie uruchomienie nie przyniosło nowych odczytów, więc pokazuję 25 najświeższych odczytów z największymi niespodziankami.",
  // ---- Data health ----
  "Series status":"Stan szeregów", "Series OK":"Szeregi OK", "Overdue":"Opóźnione", "Stopped":"Wstrzymane", "Failed":"Z błędem", "Not published":"Niepublikowane",
  "ok":"ok", "overdue":"opóźniony", "stopped":"wstrzymany", "failed":"błąd",
  // ---- Assumptions ----
  "Effect of these settings":"Skutek tych ustawień", "Reset to defaults":"Przywróć domyślne", "Go back to the default settings":"Wróć do ustawień domyślnych", "Engine file":"Plik silnika",
  "As published in the data file; its policy stance is monetary only":"Jak w opublikowanym pliku danych; nastawienie polityki jest tam tylko pieniężne", "With these settings":"Przy tych ustawieniach", "Change":"Zmiana", "Zone now":"Strefa teraz",
  "Recession risk, %":"Ryzyko recesji, %", "Headline weights":"Wagi wskaźników głównych", "Share":"Udział", "Dial":"Tarcza", "fixed":"stała",
  "Relative weight; the shares are normalised to add up to 100%":"Waga względna; udziały są normalizowane do 100%", "Latest group dial, read in this gauge's direction":"Ostatnia tarcza grupy, czytana w kierunku tego wskaźnika",
  "Latest group dial, read in this gauge":"Ostatnia tarcza grupy, czytana w kierunku tego wskaźnika",
  "How much each group counts in its gauge. Weights are relative: 2, 1, 1, 1 gives the first group 40%. A weight of 0 drops the group. Policy stance has two parts: the monetary policy group and the fiscal impulse (scored as a robust z, sign reversed), 3 to 1 by default, so the Engine file column differs for policy. Prices has a single group.":"Ile każda grupa waży we wskaźniku. Wagi są względne: 2, 1, 1, 1 daje pierwszej grupie 40%. Waga 0 usuwa grupę. Nastawienie polityki ma dwie części: grupę polityki pieniężnej i impuls fiskalny (oceniany jako odporny z, ze znakiem odwróconym), domyślnie 3 do 1, więc kolumna Plik silnika różni się dla polityki. Ceny mają jedną grupę.",
  "Recession composite":"Indeks złożony recesji", "Combine by":"Łącz przez", "average (engine default)":"średnią (domyślnie w silniku)", "highest of the parts":"najwyższą ze składowych",
  "Needles and arrows":"Wskazówki i strzałki", "Dashed needle shows the reading":"Przerywana wskazówka pokazuje odczyt sprzed", "Blue arrow shows the move over the last":"Niebieska strzałka pokazuje zmianę w ciągu ostatnich",
  "1 month ago":"1 miesiąca", "3 months ago (default)":"3 miesięcy (domyślnie)", "6 months ago":"6 miesięcy", "12 months ago":"12 miesięcy", "24 months ago":"24 miesięcy",
  "3 months ago":"3 miesięcy", "1 month ago (default)":"1 miesiąca (domyślnie)", "6 months ago (default)":"6 miesięcy (domyślnie)", "12 months ago (default)":"12 miesięcy (domyślnie)", "24 months ago (default)":"24 miesięcy (domyślnie)",
  "1 month":"1 miesiąca", "3 months":"3 miesięcy", "6 months":"6 miesięcy", "12 months":"12 miesięcy", "3 months (default)":"3 miesięcy (domyślnie)", "1 month (default)":"1 miesiąca (domyślnie)",
  "6 months (default)":"6 miesięcy (domyślnie)", "12 months (default)":"12 miesięcy (domyślnie)",
  "Applies to every gauge and group dial and to their captions. The movers lines keep the engine's 3-month window.":"Dotyczy każdego wskaźnika i tarczy grupy oraz ich podpisów. Linie największych zmian zachowują 3-miesięczne okno silnika.",
  "Regime compass cut-offs":"Progi kompasu reżimów", "Growth z cut-off":"Próg z wzrostu", "Price-pressure z cut-off":"Próg z presji cenowej",
  "Where the four quadrants of the compass split: a month is Overheating when its growth z is at or above the growth cut-off and its price-pressure z at or above the price cut-off, Stagflation when growth is below and prices above, and so on. The engine centres both at 0; moving them, say to 0.3 and 0.3, demands a clearer signal before a month leaves the central quadrant it would otherwise sit in. Shared with the History tab, where the cut-offs colour the canvas and split the statistics.":"Gdzie dzielą się cztery ćwiartki kompasu: miesiąc to Przegrzanie, gdy jego z wzrostu jest na progu wzrostu lub powyżej, a z presji cenowej na progu cen lub powyżej; Stagflacja, gdy wzrost jest poniżej, a ceny powyżej, i tak dalej. Silnik ustawia oba progi na 0; przesunięcie ich, np. do 0.3 i 0.3, wymaga wyraźniejszego sygnału, zanim miesiąc opuści ćwiartkę, w której inaczej by się znalazł. Wspólne z zakładką Historia, gdzie progi barwią tło i dzielą statystyki.",
  "Zone cut-offs":"Progi stref", "Where one zone ends and the next begins. They change the colours, zone names and zone shares everywhere, not the gauge values. Cut-offs must rise from left to right.":"Gdzie kończy się jedna strefa i zaczyna następna. Zmieniają kolory, nazwy i udziały stref wszędzie, ale nie wartości wskaźników. Progi muszą rosnąć od lewej do prawej.",
  "Dial family":"Rodzina tarcz", "Zones":"Strefy", "Cut-offs":"Progi", "Group members":"Członkowie grup",
  "Untick a series to drop it from its group, or change its weight. The engine weights every member equally. Dropped series also leave the gauges and the member tables.":"Odznacz szereg, aby usunąć go z grupy, albo zmień jego wagę. Silnik waży każdego członka jednakowo. Usunięte szeregi znikają też ze wskaźników i tabel członków.",
  "Share now":"Udział teraz", "Relative weight inside the group (0 to 5); 1 is the engine default":"Waga względna w grupie (0 do 5); 1 to wartość domyślna silnika", "Share of the group dial in the latest month":"Udział w tarczy grupy w ostatnim miesiącu",
  "Score in the latest month, read in the dial direction":"Wynik w ostatnim miesiącu, czytany w kierunku tarczy",
  "Fixed in the engine":"Stałe w silniku", "These are part of the published method and change only with the engine (macro_score.py, macro_composite.py).":"To część opublikowanej metody i zmienia się tylko wraz z silnikiem (macro_score.py, macro_composite.py).",
  "Indicator z-score":"Wynik z wskaźnika", "Robust: (x − rolling median) / (1.4826 × MAD), standard deviation where the MAD is zero":"Odporny: (x − krocząca mediana) / (1.4826 × MAD), odchylenie standardowe tam, gdzie MAD jest zerem",
  "Window":"Okno", "Rolling 10 years (3,653 days), expanding from a 5-year minimum, no score before 5 years":"Kroczące 10 lat (3653 dni), rozszerzane od minimum 5 lat, bez wyniku przed upływem 5 lat",
  "Clip":"Obcięcie", "Each indicator score is clipped at ±3 before averaging":"Wynik każdego wskaźnika jest obcinany do ±3 przed uśrednieniem", "Minimum members":"Minimalna liczba członków",
  "A group needs at least three members with a reading in the month (or all of them if it has fewer)":"Grupa potrzebuje co najmniej trzech członków z odczytem w danym miesiącu (albo wszystkich, jeśli ma ich mniej)",
  "Carry-forward":"Przenoszenie", "Daily and weekly 1 month, monthly 3, quarterly 3 after the quarter (5 from its first month), annual 12 after the year":"Dzienne i tygodniowe 1 miesiąc, miesięczne 3, kwartalne 3 po kwartale (5 od jego pierwszego miesiąca), roczne 12 po roku",
  "Polarity and transforms":"Kierunki i przekształcenia", "Set per series in series.json (see the Technical appendix catalogue)":"Ustalane dla każdego szeregu w series.json (zob. katalog w Aneksie technicznym)",
  "100 × Φ(z), the standard normal distribution function":"100 × Φ(z), dystrybuanta standardowego rozkładu normalnego", "Movers window":"Okno największych zmian",
  "Economy and activity groups (output, labor, consumer, housing)":"Gospodarka i grupy aktywności (produkcja, rynek pracy, konsumpcja, mieszkalnictwo)", "Policy stance and policy group":"Nastawienie polityki i grupa polityki",
  "Financial conditions and credit group":"Warunki finansowe i grupa kredytu", "Price pressure and inflation group":"Presja cenowa i grupa inflacji", "Markets and financial stress group":"Grupa rynków i napięć finansowych",
  "Fiscal impulse, pp of GDP":"Impuls fiskalny, pkt proc. PKB", "Fiscal impulse, pp":"Impuls fiskalny, pkt proc.",
  // ---- scoring transforms (TF_NAME) ----
  "level":"poziom", "y/y %":"% r/r", "q/q SAAR %":"% kw/kw, w ujęciu rocznym", "12-month change":"zmiana 12-miesięczna", "3-month average of the monthly change":"średnia 3-miesięczna zmiany miesięcznej",
  "4-week average":"średnia 4-tygodniowa", "13-week % change":"zmiana % w 13 tygodni", "% below its 12-month high":"% poniżej 12-miesięcznego maksimum", "% of GDP":"% PKB", "12-month sum, % of GDP":"suma 12-miesięczna, % PKB",
  "policy rate minus core PCE y/y":"stopa polityki minus bazowe PCE r/r", "minus IORB":"minus IORB", "per unemployed person":"na osobę bezrobotną", "VIX / VXV ratio":"relacja VIX / VXV",
  "change over a year":"zmiana w ciągu roku", "previous year = 100, minus 100":"rok poprzedni = 100, minus 100", "12-month sum":"suma 12-miesięczna"
};
// text with numbers, matched as a whole (first match wins)
const PL_RX = [
  [/^(\d+) indicators? in (\d+) groups?$/, (m,a,b)=>`${a} ${plN(a,"wskaźnik","wskaźniki","wskaźników")} w ${b} ${plN(b,"grupie","grupach","grupach")}`],
  [/^(\d+) indicators?(?: matching "(.*?)")?(?: in (.*?))?(, scored only)?$/, (m,a,q,g,s)=>`${a} ${plN(a,"wskaźnik","wskaźniki","wskaźników")}`+(q?` pasujących do „${q}”`:"")+(g?` w grupie ${g}`:"")+(s?", tylko oceniane":"")],
  [/^(\d+) of (\d+) members live$/, "$1 z $2 członków z odczytem"],
  [/^dial (.+)$/, "tarcza $1"],
  [/^(\d+) series with a new or revised observation in the latest pipeline run\.$/, (m,a)=>`${a} ${plN(a,"szereg","szeregi","szeregów")} z nową lub zrewidowaną obserwacją w ostatnim uruchomieniu.`],
  [/^(\d+)-month movers: (.*)$/, "Największe zmiany w $1 mies.: $2"],
  [/^(\d+)-month movers$/, "Największe zmiany w $1 mies."],
  [/^([\d.\-+]+): (.+) below, (.+) above$/, "$1: poniżej $2, powyżej $3"],
  [/^([\d.\-+]+): low below$/, "$1: niskie poniżej"], [/^([\d.\-+]+): high above$/, "$1: wysokie powyżej"],
  [/^\(growth z (.+), price z (.+)\)$/, "(z wzrostu $1, z cen $2)"],
  [/^(\d+) months earlier: (.+)$/, "$1 mies. wcześniej: $2"],
  [/^(.+) \(start of the blue arrow; moves under 22 degrees of arc are drawn at that minimum length, no change shows as a small blue ring\) · (.+) \(dashed needle\)$/, (m,a,b)=>`${trAgo(a)} (początek niebieskiej strzałki; ruchy poniżej 22 stopni łuku są rysowane w tej minimalnej długości, brak zmiany to mały niebieski pierścień) · ${trAgo(b)} (przerywana wskazówka)`],
  [/^(.+) · (\d+)m ([+\-−–][\d.]*|–) · (\d+)m ago (.+)$/, "$1 · $2 mies. $3 · $4 mies. temu $5"],
  [/^(.+): change in its signed, clipped z over (\d+) months, divided by the group size and headline weight\. Current indicator z (.+)\.$/, "$1: zmiana jego obciętego z ze znakiem w ciągu $2 mies., podzielona przez liczebność grupy i wagę wskaźnika. Bieżący z wskaźnika $3."],
  [/^(.+): (.+) \((.+)\), (\S+ \d{4}) · (\d+) of (\d+) members live\. Click to open this group's members; click again to close\.$/, "$1: $2 ($3), $4 · $5 z $6 członków z odczytem. Kliknij, aby otworzyć członków grupy; kliknij ponownie, aby zamknąć."],
  [/^(.+): (.+) pp of GDP \((.+)\), (\S+ \d{4})\. Click to open the fiscal detail; click again to close\.$/, "$1: $2 pkt proc. PKB ($3), $4. Kliknij, aby otworzyć szczegóły fiskalne; kliknij ponownie, aby zamknąć."],
  [/^Share of the (.+) gauge \(Assumptions tab\)$/, "Udział we wskaźniku: $1 (zakładka Założenia)"],
  [/^Contribution = the indicator's score \(signed to read like this gauge, clipped at ±3\) times its weight\. The contributions add up to the gauge's z-score \((.+)\); points are the approximate effect on the 0 to 100 reading\. Sorted from most supportive to most negative\. Click a row to unfold its charts\.$/,
    "Wkład = wynik wskaźnika (ze znakiem jak w tym wskaźniku głównym, obcięty do ±3) razy jego waga. Wkłady sumują się do wyniku z wskaźnika ($1); punkty to przybliżony wpływ na odczyt w skali od 0 do 100. Posortowane od najbardziej wspierających do najbardziej ujemnych. Kliknij wiersz, aby rozwinąć jego wykresy."],
  [/^Group dial since (\d{4}): (.+)$/, "Tarcza grupy od $1 r.: $2"],
  [/^Member scores, last (\d+) months: (.+)$/, "Wyniki członków, ostatnie $1 miesiące: $2"],
  [/^(.+): behind the gauge, last (\d+) months$/, "$1: za wskaźnikiem, ostatnie $2 miesiące"],
  [/^(.+): level as published, 10 years$/, "$1: poziom, jak opublikowano, 10 lat"], [/^(.+): momentum, last 12 changes$/, "$1: dynamika, ostatnie 12 zmian"], [/^(.+): standing, robust z, 10 years$/, "$1: pozycja, odporny z, 10 lat"],
  [/^(\S+ \d{4}): growth z (.+), price z (.+) · inner circle = 1, rim = 2 or more( · cut-offs .+)?$/, (m,a,b,c,d)=>`${a}: z wzrostu ${b}, z cen ${c} · okrąg = 1, obrzeże ≥ 2`+(d?d.replace(" · cut-offs "," · progi "):"")],
  [/^(\S+ \d{4}) to (\S+ \d{4}), (\d+) months\. Regime of a month = the compass quadrant of its growth and price-pressure z \(cut-offs (.+) and (.+)\); months before the compass starts or without both scores are "no regime reading"\. Means and standard deviations are over the monthly means of each series within the regime's months\.$/,
    "$1 do $2, $3 mies. Reżim miesiąca = ćwiartka kompasu według z wzrostu i z presji cenowej (progi $4 i $5); miesiące przed początkiem kompasu lub bez obu wyników mają „brak odczytu reżimu”. Średnie i odchylenia standardowe liczone są ze średnich miesięcznych każdego szeregu w miesiącach danego reżimu."],
  [/^canvas: regime compass quadrant by month \(growth z cut-off (.+), price z cut-off (.+)\); grey = no compass reading; paled outside (.+) to (.+)$/, "tło: ćwiartka kompasu reżimów w każdym miesiącu (próg z wzrostu $1, próg z cen $2); szare = brak odczytu kompasu; wyblakłe poza zakresem $3 do $4"],
  [/^averaged, value (.+)$/, "uśredniany, wartość $1"],
  [/^engine robust z, rolling 10 years · bands ±1 and ±2( · drawn capped at ±6)?$/, (m,a)=>"odporny z silnika, kroczące 10 lat · pasma ±1 i ±2"+(a?" · rysowany z ograniczeniem do ±6":"")],
  [/^group dial, 0-100, read as (.+)$/, "tarcza grupy, 0-100, czytana jako $1"],
  [/^growth z (.+) · price-pressure z (.+)$/, "z wzrostu $1 · z presji cenowej $2"],
  [/^headline z (.+)$/, "z wskaźnika $1"],
  [/^higher than (.+)% of months since (\d{4})$/, "wyżej niż w $1% miesięcy od $2 r."],
  [/^last (\d+) (monthly|quarterly|weekly|daily|annual) changes of the scored value · green reads stronger$/, (m,a,f)=>`ostatnie ${a} zmian ${({monthly:"miesięcznych",quarterly:"kwartalnych",weekly:"tygodniowych",daily:"dziennych",annual:"rocznych"})[f]} ocenianej wartości · zielony oznacza wzmocnienie`],
  [/^last (\d+)y$/, "ostatnie $1 lat"],
  [/^score (.+) → (.+) on the dial scale \((.+)\)$/, "wynik $1 → $2 na skali tarczy ($3)"],
  [/^zone shares: months since (\d{4}) spent in each zone$/, "udziały stref: miesiące od $1 r. w każdej strefie"],
  [/^Share of months since (\d{4}) now$/, "Udział miesięcy od $1 r. teraz"],
  [/^Share of (the )?history since (\d{4}) at or below the latest (scored value|x)$/, (m,a,y,w)=>`Udział historii od ${y} r. na poziomie ostatniej ${w==="x"?"wartości x":"ocenianej wartości"} lub poniżej`],
  [/^(\d{4}-\d{2}-\d{2}): change$/, "$1: zmiana"],
  [/^(\S+ \d{4}): (.+) \((.+)\) · z (.+)$/, "$1: $2 ($3) · z $4"],
  [/^All settings are the defaults: every number is the engine's except the policy stance, which this page blends with the fiscal impulse \((\d+)% monetary, (\d+)% fiscal\)\. Changes apply to this page only \(and to an HTML snapshot you save\)\. They never touch the published data file\.$/,
    "Wszystkie ustawienia są domyślne: każda liczba pochodzi z silnika poza nastawieniem polityki, które ta strona łączy z impulsem fiskalnym ($1% pieniężna, $2% fiskalna). Zmiany dotyczą tylko tej strony (i zapisanej migawki HTML). Nigdy nie zmieniają opublikowanego pliku danych."],
  [/^(.+) since (\d{4})$/, "$1 od $2 r."],
  [/^(\d+) settings? changed:$/, (m,a)=>`Zmienione ustawienia (${a}):`]
];
function trAgo(s){ return String(s).replace(/(\d+) months? ago/g,(m,n)=>`${n} mies. temu`); }
const PL_HTML = {};
