// ---------------- static notes in both languages (filled into [data-i18n] elements at start) ----------------
const ZCHIPS = () => `<span class="zchip" style="background:rgba(240,185,95,0.55)">${TR("Overheating")}</span> <span class="zchip" style="background:rgba(220,110,120,0.6)">${TR("Stagflation")}</span> <span class="zchip" style="background:rgba(110,160,220,0.5)">${TR("Slowdown")}</span> <span class="zchip" style="background:rgba(120,190,140,0.55)">${TR("Goldilocks")}</span>`;
const NOTES = {
  instr:{en:()=>"How to read: each card holds one headline gauge (economy, price pressure, policy stance, financial conditions, recession risk); the lines next to or under it are its groups, each with its value, zone, recent change and a 24-month colour strip. Rings run from 0 to 100 (fiscal in pp of GDP, recession risk in %), the coloured zones show how many months of the history sat in each band, the black needle is the latest month, the blue arrow the move over the last 3 months and the dashed needle 3 months earlier"+(MC_SITE_MODE?".":" (both adjustable on the Assumptions tab)."),
         pl:()=>"Jak czytać: każda karta zawiera jeden wskaźnik główny (gospodarka, presja cenowa, nastawienie polityki, warunki finansowe, ryzyko recesji); linie obok lub pod nim to jego grupy, każda z wartością, strefą, ostatnią zmianą i 24-miesięcznym paskiem kolorów. Skale biegną od 0 do 100 (impuls fiskalny w pkt proc. PKB, ryzyko recesji w %), kolorowe strefy pokazują, ile miesięcy historii przypadło na każdy przedział, czarna wskazówka to ostatni miesiąc, niebieska strzałka to zmiana w ostatnich 3 miesiącach, a przerywana wskazówka to odczyt sprzed 3 miesięcy"+(MC_SITE_MODE?".":" (oba ustawienia można zmienić w zakładce Założenia).")},
  mheat:{en:"Score = robust z signed by the indicator's polarity and by the dial direction, clipped at &plusmn;3. Each cell is coloured by the dial zone that score would give on its own (100 &times; &Phi;(score)), using the group dial's zone colours. The group dial is 100 &times; &Phi; of the average score of the members with a reading (at least three). Members are sorted by their latest score.",
         pl:"Wynik = odporny wynik z ze znakiem kierunku wskaźnika i kierunku tarczy, obcięty do &plusmn;3. Każda komórka ma kolor strefy, jaką dałby sam ten wynik (100 &times; &Phi;(wynik)), w kolorach stref tarczy grupy. Tarcza grupy to 100 &times; &Phi; ze średniego wyniku członków, którzy mają odczyt (co najmniej trzech). Członkowie są posortowani według ostatniego wyniku."},
  members:{en:"Click a row to unfold its level, momentum and standing charts. Unscored display series and helper series are not listed.",
           pl:"Kliknij wiersz, aby rozwinąć wykresy poziomu, dynamiki i pozycji. Szeregi tylko do wglądu (bez oceny) i szeregi pomocnicze nie są tu wymienione."},
  fheat:{en:"Headline gauges in bold, their groups below them in grey. Each cell takes the colour of the zone the reading fell in that month, as on the dials above; the number is the reading. Hover for details.",
         pl:"Wskaźniki główne pogrubione, ich grupy poniżej na szaro. Każda komórka ma kolor strefy, w którą wpadł odczyt w danym miesiącu, jak na tarczach powyżej; liczba to odczyt. Najedź kursorem, aby zobaczyć szczegóły."},
  hist:{en:()=>`Monthly means of the chosen series (${L(CP.histDefaultTxt)} by default; add any published series, on the right axis if its units differ) over a canvas coloured by the regime compass quadrant of each month: ${ZCHIPS()}, grey where the compass has no reading (before the scores start or a missing score). Choose a range of months: everything outside it is paled, and the table below describes the range only. The regime cut-offs (the growth and price-pressure z at which the quadrants split, 0 and 0 by default) ${MC_SITE_MODE?"also move the compass on the Radar tab.":"are shared with the Assumptions tab and move the compass on the Radar tab as well."}`,
        pl:()=>`Średnie miesięczne wybranych szeregów (domyślnie ${L(CP.histDefaultTxt)}; można dodać dowolny publikowany szereg, na prawej osi, jeśli ma inne jednostki) na tle zabarwionym według ćwiartki kompasu reżimów w każdym miesiącu: ${ZCHIPS()}, szare tam, gdzie kompas nie ma odczytu (przed początkiem wyników albo przy brakującym wyniku). Wybierz zakres miesięcy: wszystko poza nim jest wyblakłe, a tabela poniżej opisuje tylko ten zakres. Progi reżimów (wartości z wzrostu i presji cenowej, przy których dzielą się ćwiartki, domyślnie 0 i 0) ${MC_SITE_MODE?"przesuwają też kompas w zakładce Radar.":"są wspólne z zakładką Założenia i przesuwają też kompas w zakładce Radar."}`},
  fnd:{en:()=>`Every word must match (id, name, ${L(CP.fullTitle)}, group or units). Press Enter or Search; an empty search lists everything.`,
       pl:()=>`Każde słowo musi pasować (identyfikator, nazwa, ${L(CP.fullTitle)}, grupa lub jednostki). Naciśnij Enter lub Szukaj; puste wyszukiwanie pokazuje wszystko.`},
  fndRes:{en:()=>`Click a row to unfold its level, momentum and standing charts, with the ${L(CP.findDesc)} and link. Score = the indicator's z signed to read like its gauge, clipped at &plusmn;3; display-only series are shown but not scored.`,
          pl:()=>`Kliknij wiersz, aby rozwinąć wykresy poziomu, dynamiki i pozycji wraz z opisem (${L(CP.findDesc)}) i odnośnikiem. Wynik = z wskaźnika ze znakiem odpowiadającym kierunkowi jego wskaźnika głównego, obcięty do &plusmn;3; szeregi tylko do wglądu są pokazane, ale bez oceny.`},
  chg:{en:()=>`Click a row to unfold its level, momentum and standing charts. Surprise = latest scored value minus the average of the previous six prints (twenty for daily series), in units of the 10-year robust scale. Pctile = share of the history${CP.pctSince?" since "+CP.pctSince:""} at or below the latest value. Green: the move reads stronger (for policy rows, tighter); red: weaker or more stress.`,
       pl:()=>`Kliknij wiersz, aby rozwinąć wykresy poziomu, dynamiki i pozycji. Niespodzianka = ostatnia oceniana wartość minus średnia sześciu poprzednich odczytów (dwudziestu dla szeregów dziennych), w jednostkach 10-letniej odpornej skali. Centyl = udział historii${CP.pctSince?" od "+CP.pctSince+" r.":""} na poziomie ostatniej wartości lub poniżej. Zielony: zmiana oznacza wzmocnienie (dla wierszy polityki: zacieśnienie); czerwony: osłabienie lub większe napięcie.`},
  health:{en:()=>`One row per published series. Health compares the latest observation with the date the next print is due (period end + observed release lag + grace). ${L(CP.healthNote)}`,
          pl:()=>`Jeden wiersz na publikowany szereg. Stan porównuje ostatnią obserwację z datą, do której powinien pojawić się kolejny odczyt (koniec okresu + obserwowane opóźnienie publikacji + margines). ${L(CP.healthNote)}`},
  hint:{en:"&#9757; Click a large gauge to open its groups and every indicator with its contribution, or a group line to open that group's members. Click again or Close to clear.",
        pl:"&#9757; Kliknij duży wskaźnik, aby otworzyć jego grupy i każdy składnik z jego wkładem, albo linię grupy, aby otworzyć jej członków. Kliknij ponownie lub Zamknij, aby wyczyścić."}
};
function fillNotes(){
  document.querySelectorAll("[data-i18n]").forEach(el=>{ const n=NOTES[el.dataset.i18n]; if(!n) return; const v=L(n); el.innerHTML=(typeof v==="function")?v():v; });
}
